### ISSUE TITLE
questions re. RESTART options in GEOSldas

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#108]
@smahanam 

I have a couple of questions re. the RESTART options in GEOSldas.

1)  Re. option 1, it looks like the help text in the "exe inp" file is not complete.  Specifically, in lines ~1500 of "ldas_setup" (branch WJ_ldassa_regrid):

    print '# RESTART: 1                                               #'
    print '#   YES, have restart file(s) from GEOSldas *or* LDASsa    #'
    print '#        on the SAME grid                                  #'
    print '#   Must specify RESTART_ID, RESTART_PATH, RESTART_DOMAIN, #'
    print '#     with restarts stored as follows:                     #'
    print '#     RESTART_PATH/RESTART_ID/output/RESTART_DOMAIN/rs/    #'
    print '#   GEOSldas-produced restarts must be on the same         #'
    print '#     GRID and for the same or a larger domain.            #'    
    print '#   LDASsa-produced restarts must be on the same           #'
    print '#     GRID and for the GLOBAL domain (only!).              #'    

From looking at the code, I understand that the source and target restart also MUST have the same bcs and the same WEMIN values.  But this is not clear from the help message and should probably added to the help message.

2) Re. option 2:

    print '# RESTART: 2                                               #'
    print '#   YES, have restart file(s) from GEOSldas *or* LDASsa    #'
    print '#        on a DIFFERENT grid                               #'
    print '#   Must specify RESTART_ID, RESTART_PATH, RESTART_DOMAIN, #'
    print '#     with restarts stored as follows:                     #'
    print '#     RESTART_PATH/RESTART_ID/output/RESTART_DOMAIN/rs/    #'
    print '#   RESTART_DOMAIN must be GLOBAL.                         #'

From looking at the code, I understand that switching bcs does NOT work correctly for LDASsa restarts because the script does not know or find the **_source_** bcs.  That is, if the LDASsa restart was based on bcs that are different from the target bcs, then the restart variables will not be scaled properly.
Perhaps the easiest solution would be to restrict option 2 to **_only_** GEOSldas restarts, where we don't need to know the source bcs.  (I assume that the numbers needed for scaling the restart variables are all contained in "catch_internal_rst" restarts.)

Please advise, Rolf

**Comment by gmao-rreichle** [comment]
PS: Here is another question:  It looks like mk_LDASsaRestarts does not necessarily involve (old) LDASsa restarts.  There seem to be use cases where only GEOSldas "catch_internal_rst" files are involved.  Can we rename the script accordingly to avoid mistakes?  Perhaps: "mk_LDASRestarts"?

**Comment by smahanam** [comment]
> @smahanam
> 
> I have a couple of questions re. the RESTART options in GEOSldas.
> 
> 1. Re. option 1, it looks like the help text in the "exe inp" file is not complete.  Specifically, in lines ~1500 of "ldas_setup" (branch WJ_ldassa_regrid):
>    print '# RESTART: 1                                               #'
>    print '#   YES, have restart file(s) from GEOSldas _or_ LDASsa    #'
>    print '#        on the SAME grid                                  #'
>    print '#   Must specify RESTART_ID, RESTART_PATH, RESTART_DOMAIN, #'
>    print '#     with restarts stored as follows:                     #'
>    print '#     RESTART_PATH/RESTART_ID/output/RESTART_DOMAIN/rs/    #'
>    print '#   GEOSldas-produced restarts must be on the same         #'
>    print '#     GRID and for the same or a larger domain.            #'
>    print '#   LDASsa-produced restarts must be on the same           #'
>    print '#     GRID and for the GLOBAL domain (only!).              #'
> 
> From looking at the code, I understand that the source and target restart also MUST have the same bcs and the same WEMIN values. But this is not clear from the help message and should probably added to the help message.
> 
> 1. Re. option 2:
>    print '# RESTART: 2                                               #'
>    print '#   YES, have restart file(s) from GEOSldas _or_ LDASsa    #'
>    print '#        on a DIFFERENT grid                               #'
>    print '#   Must specify RESTART_ID, RESTART_PATH, RESTART_DOMAIN, #'
>    print '#     with restarts stored as follows:                     #'
>    print '#     RESTART_PATH/RESTART_ID/output/RESTART_DOMAIN/rs/    #'
>    print '#   RESTART_DOMAIN must be GLOBAL.                         #'
> 
> From looking at the code, I understand that switching bcs does NOT work correctly for LDASsa restarts because the script does not know or find the **_source_** bcs. That is, if the LDASsa restart was based on bcs that are different from the target bcs, then the restart variables will not be scaled properly.
> Perhaps the easiest solution would be to restrict option 2 to **_only_** GEOSldas restarts, where we don't need to know the source bcs. (I assume that the numbers needed for scaling the restart variables are all contained in "catch_internal_rst" restarts.)
> 
> Please advise, Rolf

**Comment by gmao-rreichle** [comment]
@smahanam , did you intend to just close this issue?

Re. my 2nd question about option 2, we do need to also think about how we can deal with the WEMIN in/out values.   If someone is using a source restart from MERRA-2, the WEMIN_in value should be 26.

**Comment by smahanam** [comment]
> 1. Re. option 1, it looks like the help text in the "exe inp" file is not complete.  Specifically, in lines ~1500 of "ldas_setup" (branch WJ_ldassa_regrid):
> From looking at the code, I understand that the source and target restart also MUST have the same bcs and the same WEMIN values. But this is not clear from the help message and should probably added to the help message.

Since Option 1 does not scale restarts, unless we go further step and make changes to scale if WEMIN from old restarts and new experiment are inconsistent, we don't need to worry about the help message for RESTART: 1. 

> 
> 1. Re. option 2:
>    print '# RESTART: 2                                               #'
> From looking at the code, I understand that switching bcs does NOT work correctly for LDASsa restarts because the script does not know or find the **_source_** bcs. That is, if the LDASsa restart was based on bcs that are different from the target bcs, then the restart variables will not be scaled properly.

mk_LDASsaRestarts reads input land parameters from rc_out/*/*/*catparam* in RESTART directory, and that are used to scale soil moisture and GHTCNT. 

As you know, WEM change is associated with the source code tag, not the BCs used. 
We used the BCS-based approach to select WEMs in regrid.pl for the AGCM since there is no other way to determine it easily for regrid.pl. As for ldas_setup, help message can use reichle-LDASsa_m3 or GEOSldas-m4 tag names to recommend suitable WEMs

> Perhaps the easiest solution would be to restrict option 2 to **_only_** GEOSldas restarts, where we don't need to know the source bcs. (I assume that the numbers needed for scaling the restart variables are all contained in "catch_internal_rst" restarts.)

Restarts files that people have at the moment are from LDASsa. So during this LDASsa-to GEOSldas transition period, ability regrid LDASsa restarts is very important and useful. 
If you look carefully, ldas_setup actually does not allow people to communicate the choice of WEMs to ldas_setup. People use sample script to make changes to options, but the current sample does not show WEMIN/WEMOUT - it is intentionally hidden (a decision you, JP and WJ made a while back).

I think offline driver has moved away from 26 long enough not to worry about it.

**Comment by smahanam** [comment]
> PS: @smahanam Here is another question: It looks like mk_LDASsaRestarts does not necessarily involve (old) LDASsa restarts. There seem to be use cases where only GEOSldas "catch_internal_rst" files are involved. Can we rename the script accordingly to avoid mistakes? Perhaps: "mk_LDASRestarts"?

I'll do it now

**Comment by smahanam** [comment]
> > PS: @smahanam Here is another question: It looks like mk_LDASsaRestarts does not necessarily involve (old) LDASsa restarts. There seem to be use cases where only GEOSldas "catch_internal_rst" files are involved. Can we rename the script accordingly to avoid mistakes? Perhaps: "mk_LDASRestarts"?
> 
> I'll do it now

How about mk_GEOSldasRestarts.F90? Since the purpose of the program is to create catch[cn]_internal_rst for GEOSldas. 
It is always good to create CATCHCN restarts for LDASsa too - but in this context, the code is serving GEOSldas

**Comment by gmao-rreichle** [comment]
@smahanam 

> Since Option 1 does not scale restarts, unless we go further step and make changes to scale if 
> WEMIN from old restarts and new experiment are inconsistent, we don't need to worry about the 
> help message for RESTART: 1.

Note that I did not say we should worry about scaling for WEMIN.  I want to change the comments provided with the RESTARTS=1 option to make it explicitly clear that this option is not appropriate if bcs or WEMIN are different between the source and target restarts.  Once you have a pull request, I'll edit the text.

Re. RESTART=2

> mk_LDASsaRestarts reads input land parameters from rc_out/*/*/*catparam* in RESTART directory, > and that are used to scale soil moisture and GHTCNT.

Thanks, this is good to know!  And it explains the mysterious "pfile" variable in mk_LDASsaRestarts...  A comment or two in the program would have been helpful.

> Restarts files that people have at the moment are from LDASsa. So during this LDASsa-to GEOSldas > transition period, ability to regrid LDASsa restarts is very important and useful.

I agree, and now that I understand that bcs are handled correctly, it is best to keep the LDASsa-to-GEOSldas option when switching bcs.

> If you look carefully, ldas_setup actually does not allow people to communicate the choice of 
> WEMs to ldas_setup. People use sample script to make changes to options, but the current sample > does not show WEMIN/WEMOUT - it is intentionally hidden (a decision you, JP and WJ made a 
> while back).
> I think offline driver has moved away from 26 long enough not to worry about it.

This decision was made **_before_** we introduced RESTART=2.  At that time, GEOSldas did not offer a way to change bcs when putting together the catch restart.  Now that we have this functionality with RESTART=2, we do need to make a smart guess for the WEMIN in/out values.  The problem with the off-line system is that, unlike the ADAS, we do not query for source bcs, so it's not clear whether the input WEMIN should be 13 or 26.  
I strongly disagree with the final sentence about the offline driver having moved away from 26 long enough.  Users will likely regrid MERRA-2 restarts for several more years because there will not be a new 30+year reanalysis for several more years.

I think we now have two options:

a) Make the script smart enough to detect WEMIN_in=26 if the restart is from MERRA-2 or FP up to 5.22.  Otherwise, assume (with some optimism) that WEMIN_in=13.  Ask the user to confirm this educated guess (perhaps as part of confirming **_all_** ldas_setup inputs, that is, don't introduce the WEMIN in/out query as a separate question).

b) As part of RESTART=2, strongly recommend that spin-up is going to be needed after regridding whenever the bcs or WEMIN have changed. 

On second thought, we probably should recommend spin-up (option 2) in any case...

> How about mk_GEOSldasRestarts.F90? Since the purpose of the program is to create 
> catch[cn]_internal_rst for GEOSldas.
> It is also good to create CATCHCN restarts for LDASsa too - but in this context, the code is serving > GEOSldas

Good suggestion.  When you rename the file, make sure to use the git rename functionality (i.e., "git mv ...").

**Comment by smahanam** [comment]
> I think we now have two options:
> a) Make the script smart enough to detect WEMIN_in=26 if the restart is from MERRA-2 or FP up to 5.22. Otherwise, assume (with some optimism) that WEMIN_in=13. Ask the user to confirm this educated guess (perhaps as part of confirming **_all_** ldas_setup inputs, that is, don't introduce the WEMIN in/out query as a separate question).

ldas_setup > mk_LDASsaRestarts.F90 : still can not regrid MERRA-2 or FP restarts. 
If we think this going to be very useful, first we need to add that capability to ldas_setup.

**Comment by weiyuan-jiang** [comment]
Sarith,
Since you are going to change mk_LDASsaRestars.F90, would you please also change the subroutine read_bcs_data() so that it doesn’t not read catchCN if we only need catch? It is way too slow to read catchCN when running ldas_setup.
Thanks
Weiyuan

**Comment by gmao-rreichle** [comment]
Addressed with pull request #149
