### ISSUE TITLE
Update Fortran and CMakeLists.txt to be MAPL 2.0 consistent

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#109]
One thing that should be done is when MAPL 2.0 is used, in Fortran files:
```fortran
use MAPL_Mod
```
should become:
```fortran
use MAPL
```

And in `CMakeLists.txt` files, dependencies or references to `MAPL_Base` should become `MAPL`.

This should be pretty simple search-and-replace, but it's possible this can expose some other underlying issue (some hidden dependency).

**Comment by gmao-rreichle** [comment]
Addressed in pull request #127
