### ISSUE TITLE
convert %cs_i_indg and %cs_j_indg to simple arrays in Assim GridComp

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#111]
The fields %i_indg and %j_indg in TileCoord are w.r.t. to the global grid that cuts tiles (regardless of whether that is a cube-sphere, EASE, or lat-long grid).

The second set of fields %cs_i_indg and %cs_j_indg should be w.r.t. to the (lat/long) "hash" grid that is used to quickly identify tiles that are within the lat/long grid cell(s) of the "hash" grid. The name "cs_[x]_indg" is confusing, because the grid in question is NOT a cs grid.  Also, the current implementation actually overwrites %i_indg and %j_indg and, consequently changes their meaning.

Solution: remove %cs_i_indg and %cs_j_indg from the TileCoord structure.  In the Assim Grid Comp, use simple hash_i/j_ind arrays for "hash" functionality and leave the original %i_indg and %j_indg unchanged.

**Comment by gmao-rreichle** [comment]
@saraqzhang : For @weiyuan-jiang to work on this issue, he would need a test case for the assimilation on the cube-sphere tiles.   Please provide him with a 1-day verified GEOSldas run that is doing assimilation on the cube-sphere tiles (otherwise similar to the GLOBAL/assim test case that mimics the SMAP L4_SM system).

**Comment by saraqzhang** [comment]
@gmao-rreichle @weiyuan-jiang 
/discover/nobackup/qzhang/C180ldas/    can be used for this test. it is assimilation on cs, the forcing is FP latlon. The built is v1790beta3, on sles11.  It has 10day assimilation results.  

I am also running v1790beta4-sles12   innovation-ens24 .   I can turn assim. on for a couple of days so to get assimilation results if  you prefer to use results from this system.

**Comment by weiyuan-jiang** [comment]
After we create a lat-lon grid for landpert, we need a tile_coord being with the tile grid. However, the values (like frac_cell, frac_pfap, area) in tile_coord are not usable anymore.  Why not create a hash_tile_coord instead of creating hash_i_indg? we set all those values no_data so it won't cause any trouble in the future. It avoid making the situation worse.

**Comment by gmao-rreichle** [comment]
addressed with pull request #295
