### ISSUE TITLE
GEOSldas re-tiling functionality (RESTART=2)

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#113]
Need to merge the functionality of branch "WJ_ldassa_regrid" (RESTART=2).

To make this work without changing the GCM, include "mk_GEOSldas_restarts.F90" into the GEOSldas Applications directory (formerly, "mk_LDASsa_restarts.F90" in GCM Grid Comp "mk_restarts" directory).

Desired additional functionality: Regridding of MERRA-2 and FP restarts, incl. determining appropriate WEMIN in/out values in the script and letting the user approve, or change interactively if needed.

**Comment by gmao-rreichle** [comment]
see also related, older (and somewhat outdated) "issues" #83 and #108

**Comment by gmao-rreichle** [comment]
Two more things:
- In "mk_GEOSldas_restarts.F90", remember to skip reading data that are only needed for CatchCN when "model==CATCH".
- Once this is done, ask Scott to remove "mk_LDASsa_restarts.F90" from the GCM Grid Comp.

**Comment by gmao-rreichle** [comment]
Reminder to @gmao-rreichle : Edit explanation (help text) about RESTART options in ldas_setup (--> exe inp)

**Comment by gmao-rreichle** [comment]
Now that v17.9.0-beta.2 is released, let's focus on adding the re-tiling fixes to GEOSldas.  
Note that v17.9.0-beta.2 now includes:
    ./src/Applications/LDAS_App/mk_GEOSldasRestarts.F90
Note also discussion above and related issues #83 and #108 

I forget what we decided... Are we implementing these changes with a copy of the getids module residing in GEOSldas for now?  Alternatively, we would have to wait for the GCM to accept the getids revisions.  

In any case, we do need a working version of the revised re-tiling routines in GEOSldas before we can issue the stable v17.9.0 release, which is needed ASAP for SMAP L4_SM Version 5.

@weiyuan-jiang :  Assuming we go ahead with a copy of the getids module residing in GEOSldas for now, can you please work with @smahanam to create a pull request for my approval?

**Comment by smahanam** [comment]
I made this comment in now closed PR. I am just wondering as to whether we will need to bring mk_GEOSldasRestarts.F90 back to "mk_restarts" directory at some point in future.

We will need a tool to regrid GEOSldas produced CATCHCN restarts with properly equilibrated carbon pools to create AGCM restarts on user specified dates, then regrid.pl will need to execute mk_GEOSldas_Restarts.F90, that means we need to have mk_GEOSldasRestarts.F90 with other mk_restarts codes.

Current approach in mk_CatchCNRestatarts.F90 (AGCM) is, regrid hydrological restarts from MERRA2 while Carbon restarts are regridded from an old offline file (similar to RESTART: 0 option in ldas_setup)

**Comment by gmao-rreichle** [comment]
@smahanam : I had thought that mk_LDASasRestarts.F90 was not used by the GCM, and that it is now obsolete.  If you're talking about new functionality, I'm confident we can find a different approach that keeps some control in GEOSldas over how the re-tiling is executed, rather than relying on "program" files locked up in the GCM GridComp (which is difficult for us to edit).  Eventually, mk_restarts can perhaps provide a collection of modules (essentially, a library of subroutines), and GEOSldas and the GCM GridComp each have simple programs that exercise these subroutines. 
For now, we do need to finish updating GEOSldas so that it works with the corrected re-tiling routines at least for Catchment.  We can deal with CatchCN later.

**Comment by weiyuan-jiang** [comment]
@smahanam You have a regrid branch sitting on GCM grid comp. GCM moves ahead so much and it is impossible to merge directly. However, it is much easier to merge GCM develop branch to your regrid branch ( please try, you will find out how easy it is).  Eventually, I can merge your branch to my branch dev/GEOSldas_regrid and discuss the merge with Scott.

**Comment by weiyuan-jiang** [comment]
@smahanam It maybe easier if you make changes directly on my branch dev/GEOSldas_regrid

**Comment by smahanam** [comment]
We shall create a new branch, and checkout those 2 files from my branch.

**Comment by gmao-rreichle** [comment]
Addressed with pull request #149
