### ISSUE TITLE
Adapt "G5DAS_defs" in get_GEOS() to work with cs-gridded forcing in 'ana' from GCM Predictor segment

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#116]

**Comment by weiyuan-jiang** [comment]
I am not quite sure what is the problem here. Do you mean we need to be consistent with the way GCM reading the cs-gridded forcing?

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : This is about adding functionality for a new variant of forcing data.  You're not (yet) on the list of Assignees, so please disregard for now.

**Comment by gmao-rreichle** [comment]
This is already working, see LADAS.
