### ISSUE TITLE
add 'catch_progn_incr'  to HISTORY collection 

### ISSUE THREAD

**Issue by saraqzhang** [GEOS-ESM/GEOSldas#122]
'catch_progn_incr'  holding ldas_incr variables should be added to GEOSldas_HIST.rc.
 It should be un-commented when in the coupling configuration ( an separate issue on  GEOSldas_LDAS.rc and lenkf.j.template ) .

**Comment by gmao-rreichle** [comment]
Sara, 
Please go ahead and create a pull request based on the latest "develop" branch.
I plan to further edit GEOSldas_HIST.rc (add a minor comment) once the pull request gets to me for approval.  
- Rolf
