### ISSUE TITLE
GEOSldas "log" file

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#123]
Make sure a "log" file is available from each GEOSldas run.
From Weiyuan's email of 24 Feb 2020:
"slurm has problem to produce the log file in time.  In our GEOEldas, we move and rename the log file to the location we specified. But sometimes, when we move, the file is not there yet, or, it is still being produced"

**Comment by saraqzhang** [comment]
@weiyuan-jiang @gmao-rreichle :   it  is a  bug in lenkf.j.template ( in the new develop branch) :  line 78 :  /bin/rm  -rf  *  .  It removes everything in scratch/ including the log.txt and err.txt that are just generated and put there by slurm. so during the run we end up without log and err from the operation. 
I made test run with line 78 changed to  /bin/rm -rf  *.*  , that guaranteed log and err files not removed and in place to record run messages as expected, and later on be moved to rc_out.

**Comment by weiyuan-jiang** [comment]
OK. That reminds me of something. It was rm -f  *.*  before . That is why I chose the log file name without dot "." to avoid being deleted.   Somehow, I drop this by accident. But we have better solution now. The log file will be  generated in the right place.

**Comment by gmao-rreichle** [comment]
addressed in pull request #127
