### ISSUE TITLE
Do we need the original output any more? I believe the history output has been verified.

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#125]
@saraqzhang https://github.com/GEOS-ESM/GEOSldas/blob/f739a549f9c57b8ff22836371bbd2d733d601e0c/src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90#L1748-L1759

**Comment by saraqzhang** [comment]
Weiyuan,
I think this call also outputs ObsFcstAna  which goes to ana/.   One way to avoid redundant binary output of incr is to replace the argument “out_incr” in call output_incr_etc(…) with a local out_incr_bin = 0 ( false) , then it will only do the ObsFcstAna part, not the incr part.  I did this in my sandbox version.

Sara

**Comment by gmao-rreichle** [comment]
There is a bug in potentially having out_incr=true while HISTORY.rc doesn't call for catch_progn_incr output.
@weiyuan-jiang  will fix this.

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang :  If we're no longer using "out_incr" (and "out_incr_format"), the subroutine output_incr_etc() is essentially a wrapper for output_ObsFcstAna().  It would be helpful to get rid of output_incr_etc() and replace the call to it with the couple of things done within the "if (out_ObsFcstAna)" block.  Let me know if you have questions.

**Comment by saraqzhang** [comment]
@weiyuan-jiang @gmao-rreichle :   "out_incr" is set in .nml,  user needs to check both .nml and History.rc.   It may be better to eliminate  "out_incr"  in the code and always calculate incr_ens_avg ( currently controlled by out_incr=true) . then let history.rc alone controls whether to output incr.

**Comment by gmao-rreichle** [comment]
addressed with pull request #132
