### ISSUE TITLE
why is tavg24? it is inconsistent with the collection name

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#126]
@saraqzhang  @gmao-rreichle  https://github.com/GEOS-ESM/GEOSldas/blob/fd759b98f039d1e0ea581fcbdb27bd1fa8441d21/src/Applications/LDAS_App/GEOSldas_HIST.rc#L33

**Comment by gmao-rreichle** [comment]
fixed before branch was merged.
