### ISSUE TITLE
Change nc tools for post-proc of diagnostic output into monthly and diurnal files

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#138]
@gmao-qliu reported to me that the creation of monthly average nc files in GEOSldas post-processing is inefficient.  
As implemented, a large nc file is first created that concatenates all hourly data, and the monthly average is then computed from this file.  
Because this intermediate file can get very large (e.g., for 9-km global EASE grid output), the process is very slow.  
Qing has apparently found a way of doing this more efficiently.
@smahanam : Can you please work with @gmao-qliu to see if this can be improved?  I would hope it's straightforward to create a pull request that addresses the issue.

**Comment by smahanam** [comment]
Sure ! I'll take a look.

**Comment by smahanam** [comment]
Thanks @gmao-qliu for the fix. In fact, I had moved away from ncrcat in scripts I wrote later.
@weiyuan-jiang , as we discussed a moment ago, this is the one line fix (I have commented out old lines).
 
# create the monly average
#ncrcat -h $EXPID.$ThisCol.${YYYY}${MM}* ${EXPID}.${ThisCol}.$YYYY$MM.nc4
#ncra -h $EXPID.${ThisCol}.$YYYY$MM.nc4 $EXPID.${ThisCol}.monthly.$YYYY$MM.nc4
       
#/bin/rm $EXPID.${ThisCol}.$YYYY$MM.nc4
ncra -h $EXPID.$ThisCol.${YYYY}${MM}??_*z.nc4 ${EXPID}.${ThisCol}.$YYYY$MM.nc4

**Comment by gmao-rreichle** [comment]
Merged in pull request #141
