### ISSUE TITLE
Need "increments" output in units of soil moisture, temperature, etc

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#139]
The existing "catch_progn_incr" collection writes out soil moisture increments in terms of Catchment model prognostics variables.  Without knowing the model forecast (or the analysis) in the same variables, the increments cannot be converted into units of soil moisture, and even if we knew the model forecast it would not be simple because we do not have an offline tool to convert Catchment prognostics into soil moisture units.
The "aup" output for the SMAP system does provide the model forecast and analysis in units of soil moisture, but this output type is limited to the assimilation of SMAP (or SMOS) obs and when running on the SMAP 9-km EASE grid tiles.
For more general output of increments, we need to add a few key model "forecast" (and perhaps also "analysis") variables as "exports" in the land assim Grid Comp.  Then HISTORY can be used to write "forecast" and "analysis" variables (incl in soil moisture units), from which the increments can be derived in post-processing.
@weiyuan-jiang and @gmao-rreichle should discuss details during weekly tag-up meeting.

**Comment by saraqzhang** [comment]
@gmao-rreichle :  I just put in a pull request  #212 for this issue.  I don't know if I should revert the pull request to draft. let me know.

**Comment by gmao-rreichle** [comment]
addressed in pull request #240
