### ISSUE TITLE
Bug fix: address error in use of re-ordered tiles for cube-sphere-based assimilation

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#146]

**Comment by gmao-rreichle** [comment]
@saraqzhang : @weiyuan-jiang now knows exactly what the problem is and will fix it as soon as he can.

**Comment by saraqzhang** [comment]
@weiyuan-jiang  @gmao-rreichle 
Weiyuan, I  completed the scaling prm file and used them in testing this branch with scale=.true. The tile num problem in observations_f is fixed and  tile_id  also works properly when applying scaling prm to obs with matching tile.   So I think you can issue pull request for merging to develop branch.
Sara

**Comment by gmao-rreichle** [comment]
@saraqzhang , @weiyuan-jiang : thanks! 

@weiyuan-jiang , please go ahead and create the pull request.  With any luck, we can merge it before we (hopefully) create the beta3 pre-release.

**Comment by gmao-rreichle** [comment]
Addressed with #152
