### ISSUE TITLE
Create necessary directories in post-processing

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#175]
When extending an existing GEOSldas run, ldas_setup cannot be used to continue the run in the same directory.
In this case, it is straightforward to extend the run by editing the run scripts.
However, some directories that would have been created in ldas_setup pre-processing are missing, and are not yet created in post-processing.  Without a fix, these directories need to be created manually.
@gmao-qliu : Please let @weiyuan-jiang know which directories you had to create manually so he can add them to the list of directories that are created in post-processing.

**Comment by gmao-qliu** [comment]
@weiyuan-jiang  the YEAR and MONTH directories in cat/, ana/ and rc_out/ should be added when output files are being copied there.

**Comment by weiyuan-jiang** [comment]
During the post processing, the script usually creates the directory on the fly like
   "  if (! -e $THISDIR ) mkdir -p $THISDIR "
So I suspect that happens during the the program run when writing a file obtaining from get_io_filename.  Would you show me the error message? @gmao-qliu

**Comment by gmao-qliu** [comment]
@weiyuan-jiang there is no such line in the section of the lenkf.j that the RC and HISTORY files are being copied from scratch. The script assumes the Y****/M** directories are already created during ldas_setup. If the run is an extension beyond the original end_date, the script will crash with error msg similar to "file non-exist".

**Comment by weiyuan-jiang** [comment]
@gmao-qliu I still could not figure out what went wrong. I need a concrete error message to debug it.

**Comment by weiyuan-jiang** [comment]
@gmao-qliu Is the error related to writing out landpert check point file?

**Comment by gmao-qliu** [comment]
@weiyuan-jiang it's the sub-directories in ana/ when "writing ldas_ObsFcstAna file" and the error output is "forrtl: No such file or directory
forrtl: severe (29): file not found, unit 10, ".  Looking into this more carefully, this may not be fixable via modifying the post-processing script. You can leave it as is for now if it involves source code change.

**Comment by weiyuan-jiang** [comment]
Indeed this file is from get_io_filename. I will fix it

**Comment by gmao-rreichle** [comment]
Addressed with pull request #182
