### ISSUE TITLE
openmpi options not recognized with new g5_modules using mpt

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSldas#18]
From email conversation with @weiyuan-jiang  and @mathomp4, lenkf.j has open mpi command:
`mpirun -map-by core --mca btl ^vader  -np $numprocs $GEOSBIN/GEOSldas.x `

When executed, it throws the error:
>     MPT ERROR: invalid option: -map-by
This is similar with the mca option.

Replacing:
`mpirun -map-by core --mca btl ^vader  -np $numprocs $GEOSBIN/GEOSldas.x`
with:
`$GEOSBIN/esma_mpirun -map-by core --mca btl ^vader  -np $numprocs $GEOSBIN/GEOSldas.x`
results in the error:
> /home/jperket/project/ldas/GitTestc48/build//install/bin//esma_mpirun: mpi_type = mpt
> /usr/local/sgi/mpi/mpt-2.17/bin/mpiexec_mpt  -map-by core --mca btl ^vader -np 96 /home/jperket/project/ldas/GitTestc48/build//install/bin//GEOSldas.x 
> mpiexec_mpt error: -map-by option not supported.
> GEOSldas Run Status: -1

I'm not sure what constraints lenkf.j needs on the mpi command. The best solution is probably to keep g5_modules as is, remove/modify mpi options, and follow up with 0-diff testing to see any effects compared to LDAS's g5_modules pre-git

**Comment by mathomp4** [comment]
@JustinPerket Try removing the `-map-by core --mca btl`. Those are only Open MPI flags.

**Comment by JustinPerket** [comment]
@mathomp4 that would fix the issue. With this, GEOSldas.x does appear to run properly from a created experiment

**Comment by tclune** [comment]
Woo hoo!

**Comment by JustinPerket** [comment]
branch bug/#18-mpi-call-fix  now fixes issue
