### ISSUE TITLE
Copy LDAS.rc file into rc_out/year/month/ dir (post-processing)

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#209]
To better capture the settings of all resource parameters, GEOSldas should automatically make a time-stamped copy of the LDAS.rc file into the rc_out/year/month output directory. 
This should be done in lenkf.j.template, not ldas_setup.  Users do not usually run "ldas_setup" again  if they simply extend an existing experiment.

**Comment by gmao-rreichle** [comment]
The resulting files should look something like
   rc_out/Yyyyy/Mmm/[EXPID].ldas_LDASrc.YYYYMMDD_HHMM.txt

**Comment by weiyuan-jiang** [comment]
quote "rc_out/Yyyyy/Mmm/[EXPID].ldas_LDASrc.YYYYMMDD_HHMM.txt"  this file has always been there in GEOSldas simulation

**Comment by gmao-rreichle** [comment]
Yes, indeed it's there.  I had been looking at SMAP ops output and found no trace of this file.  I suspect it gets lost in the L4 ops system.  No further action needed for GEOSldas.  Sorry for the false alarm.
