### ISSUE TITLE
documentation update needed

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSldas#21]
1. Update readme's and tutorial for git

    - Ex, different directory structure. placement of exe and bat files, etc    

2. Update readme's and tutorial for m4_17-8 updates

**Comment by JustinPerket** [comment]
> Update readme's and tutorial for git
#34 address this

**Comment by JustinPerket** [comment]
From: https://github.com/GEOS-ESM/GEOSldas/pull/48#issuecomment-532769547 and @gmao-rreichle, we could stand to convert the pptx tutorial to something that will work with version control.
Perhaps we should develop the LDAS github wiki? There are other readme files (like history and metforcing) that could be converted to markdown / wiki pages instead.

 
> > Ew. Binary PPTX. @tclune we should probably talk about things like this entering Git. It's already there so...
> 
> Matt: I agree that this is suboptimal from a repository standpoint. But we do need some sort of presentation-quality material for tutoring the land group on GEOSldas. Having this material outside of git makes it even more difficult to keep it in sync with GEOSldas. Let me know if Tom has an issue with this, or perhaps a better solution.

**Comment by JustinPerket** [comment]
look through the tutorial, there's nothing that couldn't be converted to markdown if we wanted. Tables would be fine. If there were images, that wouldn't be a problem either. These version control pages could be the go-to place for information. The actual slides that we present don't need to be under version control, if it's duplicating/condensing information that would already be accessible through a wiki. In fact, it would be redundant, and increasing the risk we update information one document, but forget to update the other(like the powerpoint and README's now)

**Comment by JustinPerket** [comment]
We now have a very simply wiki, that links to docs in master:

https://github.com/GEOS-ESM/GEOSldas/wiki/GEOSldas-wiki

**Comment by gmao-rreichle** [comment]
Thanks for putting together the GEOSldas Wiki, Justin.  Very helpful.
A couple of minor things after a quick glance:
1) For non-experts (incl myself), the "clone" line should probably have a place-holder entry for the tag (or branch?).  
2) We probably shouldn't say "GMAO Desktops" -- I doubt this works on my Windows Desktop.  I think you mean "GMAO Linux systems" (which includes Linux desktops and shared servers).  Not sure if it works on Macs.

**Comment by gmao-rreichle** [comment]
> Looking through the tutorial, there's nothing that couldn't be converted to markdown if we wanted. Tables would be fine. If there were images, that wouldn't be a problem either. These version control pages could be the go-to place for information. The actual slides that we present don't need to be under version control, if it's duplicating/condensing information that would already be accessible through a wiki. In fact, it would be redundant, and increasing the risk we update information one document, but forget to update the other(like the powerpoint and README's now)

I agree that it's good to have more of this in a format that is readily readable on github. The checkout, build, and run instructions (now in the GEOSldas Wiki) are great.  
I'm a bit confused, though, about images.  Aren't those binary as well?  Then we'd be replacing the single pptx with lots of separate binary image files.  That doesn't seem attractive, either.  But I'm not sure I quite understand the issues. 
In any case, it is certainly ok with me to convert the pptx tutorial into Wiki material as much as possible.  Any relevant science results (graphics) could be kept outside of github.

**Comment by JustinPerket** [comment]
> Thanks for putting together the GEOSldas Wiki, Justin. Very helpful.
> A couple of minor things after a quick glance:

Right now it's not a great wiki with true pages of our own, it's just very simply linking to the README.md and older README docs in master. @mathomp4 kindly started the great wiki for us, which I have lightly edited 
https://github.com/GEOS-ESM/GEOSldas/blame/master/README.md

> 1. For non-experts (incl myself), the "clone" line should probably have a place-holder entry for the tag (or branch?).

We could add this. Perhaps we should keep the README.md fairly brief, and add more detailed/nuanced things to the wiki

> 2. We probably shouldn't say "GMAO Desktops" -- I doubt this works on my Windows Desktop.  I think you mean "GMAO Linux systems" (which includes Linux desktops and shared servers).  Not sure if it works on Macs.
Yup, we should remove this if LDAS wouldn't work (and NAS too?)




> I agree that it's good to have more of this in a format that is readily readable on github. The checkout, build, and run instructions (now in the GEOSldas Wiki) are great.
> I'm a bit confused, though, about images. Aren't those binary as well? Then we'd be replacing the single pptx with lots of separate binary image files. That doesn't seem attractive, either. But I'm not sure I quite understand the issues.

If images are in the wiki, they're not in the LDAS repository. (rather, their on their own wiki repository, and has a more simplified way of dealing with history). We can hash out details on what we want to do
