### ISSUE TITLE
Add functionality for tb_h and tb_v HISTORY output 

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#219]
Need functionality to output tb_h and tb_v (L-band brightness temperatures) through HISTORY.
Requires loading mwRTM parameters and computing tb_h, tb_v if HISTORY is calling for tb_h, tb_v output.
Currently, mwRTM_param seems to be available only in the LandAssim GridComp, where loading mwRTM parameters appears to be controlled by the logical variable "need_mwRTM_param".

This is _very_ urgently needed so we can use GEOSldas to replace an old SMAP data stream (Nature Run v03) that outputs tb_h and tb_v for the SMAP Project.  Currently, this stream uses a ~2015 version of LDASsa that is difficult to migrate to SLES12.

cc: @gmao-qliu

**Comment by weiyuan-jiang** [comment]
Now tb_h, tb_v can be output from HISTORY. It is time to consider in what situation it can be output. At this point, it requires 1) assim = .true. 2) need_mwrtm_param. 3) in HISTORY.  We need to relax the constrain.

**Comment by gmao-rreichle** [comment]
addressed with #231
