### ISSUE TITLE
About BRTHISOTRY 

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#221]
Are these ensemble average?  I saw "avg" in the name.  https://github.com/GEOS-ESM/GEOSldas/blob/5f2c6c90e939fd3dfa79a03d68c52c7fa95a6916/src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90#L2052-L2054  @gmao-rreichle

**Comment by weiyuan-jiang** [comment]
Is this also ensemble average? I guess we can ignore it for now .  https://github.com/GEOS-ESM/GEOSldas/blob/5f2c6c90e939fd3dfa79a03d68c52c7fa95a6916/src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90#L2072

**Comment by gmao-rreichle** [comment]
Please ignore the "_avg" in the variables names in lines 2052-2054 and 2072 of GEOS_LandAssimGridComp.F90.
I had copied subroutine call statements from a piece of code where the ens avg was used as input.
Here, the Tb should be calculated separately for each member.
Sorry for the confusion.
