### ISSUE TITLE
change start_time and stop_time arguments to current_time and (current_time+JOBSGMTLENGTH)

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#242]
https://github.com/GEOS-ESM/GEOSldas/blob/30c8180975d5a88103ce6f6359725480dd37f5df/src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90#L1212

can use LDASsa legace utility "augment_date_time()"  to add JOBSGMTLENGTH (in seconds) to current_time

**Comment by weiyuan-jiang** [comment]
The stop time is right. If MAPL can change the start time , we don't need any changes. https://github.com/GEOS-ESM/MAPL/issues/506

**Comment by gmao-rreichle** [comment]
addressed with #279
