### ISSUE TITLE
Update "esma_add_library ... MAPL_ ..." and "use MAPL_*"?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#253]
@mathomp4 had the following comments about upcoming MAPL changes (from  GEOSgcm_GridComp pull request [#271](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/271))

Re. CMakeLists.txt:
"_FYI: This needs to be MAPL, not MAPL_Base. With MAPL 2.2, MAPL_Base will not exist as a library target anymore._"

Re. *.F90:
"_FYI: use MAPL_Mod and use MAPL_ConstantsMod should probably go back to use MAPL. These modules might change soon, though use MAPL should always work._"

GEOSldas contains many "use MAPL_Mod" and "use MAPL_ConstantsMod" statements.  Should these be updated at this time? 

If we are updating them, the "only" qualifiers should be kept if at all possible.  E.g., replace:
  `use MAPL_ConstantsMod, only: MAPL_TICE`
with
  `use MAPL, only: MAPL_TICE`
Do not replace with just `use MAPL` unless there is a very good  reason why we would need to drop the "only" qualifier.

Do any "esma_add_library" statements require modification?

**Comment by mathomp4** [comment]
@gmao-rreichle I just consulted with @tclune. We definitely want any `esma_add_library` or similar CMake call to use `MAPL`. In fact, with MAPL 2.2, you should *only* use that as internal library names/targets are changing. But using `MAPL` works just fine with current MAPL 2.1.x

As for inside Fortran code, Tom feels there isn't really any big need to change `use MAPL_Base, only: MAPL_UNDEF` say to `use MAPL, only: MAPL_UNDEF`. It should work, but not as crucial as the CMake issue.

**Comment by gmao-rreichle** [comment]
closing based on Matt's comments
