### ISSUE TITLE
Issue with Assim Test

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#29]
I have most of the tests running, but I think I need to change something for the `assim` test:

`/gpfsm/dnb02/mathomp4/SystemTests/logs/LDAS/2019-08-16/hubglobal/run.hubglobal.log_07:58:09`

**Comment by JustinPerket** [comment]
@mathomp4. Is this because your test was original testing master (with Externals.cfg) instead of develop (with Develop.cfg)?  I will try to recreate

**Comment by JustinPerket** [comment]
I now got all git tests to run and compare (with develop branch, and Develop.cfg) Some of my comparisons with cvs failed because I didn't have current cvs tests. I will rerun /LDAS_Nightly_Cron.ManualRun.csh for all experiments

**Comment by JustinPerket** [comment]
This is what I get after running all tests

```
Full Log File: /discover/nobackup/jperket/SystemTests/logs/LDAS/2019-08-21/log.12:04:50

Runtype       CVS  Build Build Time Model Run/Compare/VCS Assim Run/Compare/VCS
-------       ---  ----- ---------- --------------------- ---------------------
conus         pass pass  14 min     pass/FAIL/ --          -- / -- / --        
global         --   --    --        pass/FAIL/ --         FAIL/FAIL/ --        
globalcs       --   --    --        pass/FAIL/ --          -- / -- / --        
globalcscn     --   --    --        pass/FAIL/ --          -- / -- / --        
L16U          pass pass   6 min     pass/pass/ --         pass/pass/ --        
hubconus       --  pass  10 min     pass/pass/pass         -- / -- / --        
hubglobal      --   --    --        pass/pass/FAIL        FAIL/pass/pass       
hubglobalcs    --   --    --        pass/pass/pass         -- / -- / --        
hubglobalcscn  --   --    --        pass/pass/pass         -- / -- / --        
```
Most of the git comparisons with cvs passed! Some observations:
- The fails for conus, global, and global* model comparisons were expected due to the bug fix in cvs UNSTABLE pending review by Rolf. 
-  global assim run failed due to running out of time
`/discover/nobackup/jperket/SystemTests/logs/LDAS/2019-08-21/global/run.global.log_12\:21\:56`
`/discover/nobackup/jperket/SystemTests/runs/LDAS_GLOBAL/assim/CURRENT/scratch/GEOSldas_log_txt`
( not finished in an hour. Is this reasonable?)
- hobglobal model cvs comparison failed:
`/discover/nobackup/jperket/SystemTests/logs/LDAS/2019-08-21/hubglobal/cmp_gitvcvs_model.hubglobal.log_15:16:27`
both lnd and lfs collections have non-zero diffs. It's odd that the hubglobal model cvs comparison failed wihen hubconus did not. Perhaps there's still a gremlin in my system test setup...

**Comment by mathomp4** [comment]
I'm back now, but it looks like everything is failing for me the last time LDAS ran. I'll have to take a look...

**Comment by weiyuan-jiang** [comment]
Are you using develop branch and Develop.cfg ?

**Comment by JustinPerket** [comment]
@mathomp4 has updated the baseline for both CVS versions, and git (keeping a backup for cvs in case we need to revert)

In one test we see the cvs global model run fail to compare with its baseline, but the git global is 0 diff with itself and the cvs baseline:

> Full Log File: /discover/nobackup/mathomp4/SystemTests/logs/LDAS/2019-08-29/log.10:57:18
> 
> Runtype       CVS  Build Build Time Model Run/Compare/VCS Assim Run/Compare/VCS
> -------       ---  ----- ---------- --------------------- ---------------------
> conus         pass pass  19 min     pass/pass/ --          -- / -- / --        
> **global         --   --    --        pass/FAIL/ --         pass/pass/ --**        
> globalcs       --   --    --        pass/pass/ --          -- / -- / --        
> globalcscn     --   --    --        pass/pass/ --          -- / -- / --        
> L16U          pass pass   7 min     pass/pass/ --         pass/pass/ --        
> **hubconus       --  pass  11 min     pass/pass/pass         -- / -- / --**        
> hubglobal      --   --    --        pass/FAIL/FAIL        pass/FAIL/pass      
> hubglobalcs    --   --    --        pass/pass/pass         -- / -- / --        
> hubglobalcscn  --   --    --        pass/pass/pass         -- / -- / --        

But in another test a few hours later (with no change to code or baseline), the cvs global run now compares 0 diff with its baseline. Meanwhile the git global model fails comparison with it's baseline, but is 0 diff with the cvs baseline:

> Full Log File: /discover/nobackup/mathomp4/SystemTests/logs/LDAS/2019-08-29/log.19:30:01
> 
> Runtype       CVS  Build Build Time Model Run/Compare/VCS Assim Run/Compare/VCS
> -------       ---  ----- ---------- --------------------- ---------------------
> conus         pass pass  17 min     pass/pass/ --          -- / -- / --        
> **global         --   --    --        pass/pass/ --         pass/pass/ --**        
> globalcs       --   --    --        pass/pass/ --          -- / -- / --        
> globalcscn     --   --    --        pass/pass/ --          -- / -- / --        
> L16U          pass pass   7 min     pass/pass/ --         pass/pass/ --        
> hubconus       --  pass  11 min     pass/pass/pass         -- / -- / --        
> hubglobal      --   --    --        pass/FAIL/pass        pass/FAIL/pass      
> hubglobalcs    --   --    --        pass/pass/pass         -- / -- / --        
> hubglobalcscn  --   --    --        pass/pass/pass         -- / -- / --        
> 

So the git baseline is different than the cvs, and both git and cvs seem to have a sporadic bug. 

The spatial pattern in the plot does not persist between tests. that also seems random, but always the affected tiles are grouped in the same gridcells

> If we can use this issue to continue to see why hubglobal is different than global for model, I gridded the tile restarts, and see a spatial patern in the differences
> 
> (sorry for the quick plot without markers, differences are primarily in South America. time is 20140102 0000)
> ![image](https://user-images.githubusercontent.com/28764984/63879839-80872d80-c99a-11e9-8552-3427cbe29013.png)

**Comment by JustinPerket** [comment]
Issue turned out to be recent change in LDAS_Forcing that got back-propagated to Git. It has been reverted.
