### ISSUE TITLE
optimize processor layout (2d)

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#306]
at the same time, look at profiling and scaling

**Comment by biljanaorescanin** [comment]
PR #316 partially addressed some of this

**Comment by gmao-rreichle** [comment]
2-d layout has been implemented (after removing bottleneck of allowing processors to have no tiles, #316).
Runtime has not yet been improved noticeably using the 2d layout.
Closing this issue.
