### ISSUE TITLE
setup for ldas coupling to adas 

### ISSUE THREAD

**Issue by saraqzhang** [GEOS-ESM/GEOSldas#307]
@gmao-rreichle @weiyuan-jiang  @biljanaorescanin 
 modification/addition to  GEOSldas setup procedure so that resulting CAP.rc LDAS.rc lenkf.j  are modified for the option of "coupling2adas" .

**Comment by gmao-rreichle** [comment]
Hi @saraqzhang : Sounds good.  When you're branch is ready, please create a "draft" pull request following the protocol here:
https://github.com/GEOS-ESM/GEOSldas/wiki/Protocol-for-GEOSldas-pull-requests

cc: @weiyuan-jiang @biljanaorescanin

**Comment by saraqzhang** [comment]
@gmao-rreichle  @weiyuan-jiang  @biljanaorescanin 
a draft pull request is created  at the branch:   feature/setup4coup

**Comment by biljanaorescanin** [comment]
Addressed with #308
