### ISSUE TITLE
Update GEOSldas to new ESMA_env (v3.0.0)

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#314]
A new ESMA_env v3.0.0 will be released soon by @mathomp4.  This will move to Intel 19.1.2. 

Action item: Test GEOSldas with the new ESMA_env release and create a matching pull request.

Changes include:

1. SLES 11 is not supported because Intel 19 can't even install on it. I could always help people who need SLES 11, but I sort of don't want people to have the ability to run on SLES 11 without having to work for it)
2. The Python stack will move to the newer Miniconda-based stack. It's still Python 2 (boo) but it's newer and, as such, some numerical differences could occur with it compared to older ones (i.e., numpy updates, etc.) if you use Python for math.
3. The Baselibs will be moved 6.0.16. This won't really affect anything that I can think of. It has a slightly newer cURL and NCO than 6.0.13, but most of the updates were in the GFE layers used by MAPL.[1]

Also, @sdrabenh is near to releasing a new zero-diff version of GEOSgcm, after which he'll make a new non-zero-diff release,  where Intel 19.1.2 is among the changes.

**Comment by mathomp4** [comment]
I've issued ESMA_env v3.0.0. I do not believe it requires any other (sub-)repos to change. 

I might make a follow up issue for @biljanaorescanin to try the latest ESMA_cmake, ecbuild, and MAPL stable versions as well. I see in `develop` you are a bit behind the GEOSgcm in those. I'm not sure they have much you need, but it's always good to keep up with patch releases.

(As an FYI the next "big" update might be MAPL 2.3, but so far it's zero-diff with the GCM.)

**Comment by biljanaorescanin** [comment]
Sure @gmao-rreichle.
I will test for:
ESMA env: tag = v3.0.0
ESMA_cmake: tag = v3.2.0
ESMA_ecbuild: tag = geos/v1.0.5
GMAO_shared: tag = v1.1.9
MAPL: tag = v2.1.6
@mathomp4 is this what you had in mind? And than if this is zero diff we will try new MAPL tag = 2.3
cc: @weiyuan-jiang

**Comment by biljanaorescanin** [comment]
This issue is addressed with pull request #315
