### ISSUE TITLE
new options on increments and forcing for HybridAdas coupling 

### ISSUE THREAD

**Issue by saraqzhang** [GEOS-ESM/GEOSldas#325]
HybridAdas has two parts to couple with ldas:  
(a) central: one set of forcing, one set of increments, ldas run at the central_fcst  resolution
(b) ensemble:  Nens sets of forcing, Nens sets of increments, ldas run at ens_fcst resolution ( lower) . 

to develop the coupling options for HybridAdas:
(1) add saving ensemble increments ( in addition to ens_avg ) so that they can be applied to  HybridAdas ensemble model integration 
(2) add accepting ensemble forcing from HybridAdas ensemble model integration 
(3) add an utility to regrid higher-resolution increments to the resolution matching HybridAdas ensemble model resolution. This is for an option to apply regrided increments to HybridAdas ensemble model integration ( without the second run of ldas at lower resolution).

**Comment by gmao-rreichle** [comment]
> (1) add saving ensemble increments ( in addition to ens_avg ) so that they can be applied to HybridAdas ensemble model integration

This was addressed in pull request #341 

> (2) add accepting ensemble forcing from HybridAdas ensemble model integration

Transferred to issue #343


> (3) add an utility to regrid higher-resolution increments to the resolution matching HybridAdas ensemble model resolution. This is for an option to apply regrided increments to HybridAdas ensemble model integration ( without the second run of ldas at lower resolution).

This is obsolete.  The hybrid 4D EnVar ADAS will run two LDAS instances, one for the (deterministic) high-res GCM and another for the low-res atmospheric ensemble.
