### ISSUE TITLE
Updating to Intel 19.1.3 and Baselibs 6.0.22: Tests Please

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#330]
We (the GCM folks) are planning to move GEOS GCM to use Intel 19.1.3 on discover (and NAS, etc.). The main reason for this is that Intel 19.1.3 seems to handle the weird build issues (random segmentation faults at compile time) plaguing the GCM on discover at present. Testing with the GCM has shown zero-diff save for MOM6 (which technically doesn't produce good science at the moment anyway).

At the same time, we are also wanting to move to Baselibs 6.0.22 (which has some updates needed for some of @weiyuan-jiang 's other work for us). 

What I'd like is if more knowledgeable LDAS devs (@biljanaorescanin and @weiyuan-jiang or even @gmao-rreichle ) could test LDAS as well, make sure it works. The "usual" way I'd do this is to change my nightly test script and run it, but the issue is that if anyone else out there was using at the time, they'd suddenly get a new compiler. 

If you feel that's fine, I can give it a try, but you all know more of what to look out for. 

For testing, there are two ways to get the new compiler. ESMA_env has a v3.1.0 release, or you can directly copy the g5_modules from:
```
/gpfsm/dhome/mathomp4/GitG5Modules/SLES12/6.0.22/g5_modules.intel1913.impi1913
```
Note: @sdrabenh is doing his own tests as well for suitability for the GCM, but I'm pretty certain that it's okay (I ran the GCM nightly tests with Intel 19.1.3 for a while and it seemed happy).

**Comment by biljanaorescanin** [comment]
@mathomp4  I am running the tests now. @gmao-rreichle  this will move Baselibs to HDF5 1.12.0, if I remember right LDAS_GLOBAL/assim test case will indicate if there are any problems with this.

**Comment by mathomp4** [comment]
@biljanaorescanin Nooo. It moves from HDF5 1.10.6 to 1.10.7. I am not moving to HDF5 1.12 without more testing. But the .6 to .7 update was *very* minor:

https://www.hdfgroup.org/2020/09/release-of-hdf5-1-10-7-newsletter-175/

But some newer machines I was testing GEOS weren't happy with 1.10.6 for reasons I never figured out.

**Comment by mathomp4** [comment]
Well, I guess "minor" more than "very minor". It mainly added new functions for people to use, but it did not do any API changes like 1.12.0 does. That one I'm approaching more carefully.

**Comment by biljanaorescanin** [comment]
@mathomp4 Ok... I didn't get that. Anyway tests are in q so we will see. I will update once done.

**Comment by mathomp4** [comment]
Here is a bit more on the update:

https://portal.hdfgroup.org/display/HDF5/New+Features+in+HDF5+Release+1.10#NewFeaturesinHDF5Release1.10-1_10_7

If anything, it should be faster according to them. And here are the new functions:

https://portal.hdfgroup.org/display/HDF5/Software+Changes+from+Release+to+Release+for+HDF5-1.10#SoftwareChangesfromReleasetoReleaseforHDF5-1.10-1_10_7

**Comment by biljanaorescanin** [comment]
All tests passed with new ESMA_env tag v3.1.0 except CatchCN related tests (since we still didn't update them.)
@mathomp4 @gmao-rreichle @weiyuan-jiang

**Comment by mathomp4** [comment]
Closing as this is now done
