### ISSUE TITLE
consistency check for number of tiles in restart file

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#344]
It looks like MAPL reads restart files without error even if the restart files contain data for more than the expected number of tiles, which results in bad simulations.

A consistency check for the number of tiles in the restart file and the location stream is needed, preferably in the MAPL code that handles the reading of restarts.

@gmao-qliu has a GEOSldas simulation in the 36-km EASEv2 tile space that was inadvertently initialized from a restart file in the 9-km EASEv2 tile space.

cc: @weiyuan-jiang @gmao-qliu @biljanaorescanin

**Comment by weiyuan-jiang** [comment]
It would be addressed by https://github.com/GEOS-ESM/MAPL/pull/648

**Comment by weiyuan-jiang** [comment]
It is addressed by https://github.com/GEOS-ESM/MAPL/pull/655

**Comment by gmao-rreichle** [comment]
This was addressed in a modification to MAPL and will be used in GEOSldas when GEOSldas updates to a newer MAPL tag.
