### ISSUE TITLE
pert cold restart in cubed grid option 

### ISSUE THREAD

**Issue by saraqzhang** [GEOS-ESM/GEOSldas#348]
@weiyuan-jiang @gmao-rreichle 
in the current DEVELOP branch build,  if the grid choice is cubed sphere, 
LDAS.rc does not have 
LANDPERT_INTERNAL_RESTART_FILE:     ../input/restart/landpert%s_internal_rst

with this setting,  ldas always perform perturbation cold start. regardless ensemble landpert rst are generated and linked in rs directory for the subsequent segment runs. 

ldas uses warm start  landpert rst  only when LANDPERT_INTERNAL_RESTART_FILE:     ../input/restart/landpert%s_internal_rst  is added to LDAS.rc.

**Comment by weiyuan-jiang** [comment]
For a "warm" restart, are those landpert files already in the ../input/restart/ folder? @saraqzhang

**Comment by saraqzhang** [comment]
yes  for warm restart the landpert rst are in input/restart/ ( they are linked to the actual files in rs/ens***/ ... ) .
current issue is that without that line ( landpert ) in LDAS.rc , those landpert files are ignored.
