### ISSUE TITLE
Possibly delete merged branches?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#36]
@JustinPerket 

You might want to look at deleting the merged branches. If we look on the repo there are quite a few that are probably not needed anymore:
<img width="1207" alt="Screen Shot 2019-09-05 at 3 11 12 PM" src="https://user-images.githubusercontent.com/2982494/64371819-83fc6380-cfef-11e9-94f1-0f8ee4c9cbd1.png">

Note if you like, I can configure this repo to delete merged branches automatically? @tclune and I haven't done that yet for fear something could go wrong but...probably nothing can. If you'd like to be a guinea pig, let me know and I can enable it.

**Comment by JustinPerket** [comment]
I'll delete the branches manually. I just wanted to keep them around for extra assurance as we were first getting set up

**Comment by JustinPerket** [comment]
merged branches (that are expected to inactive) now deleted
