### ISSUE TITLE
ESMF 8.1.0 Testing

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#368]
This is mainly a "for historical reasons" issue. ESMF has released version 8.1.0 and there is a slight chance it could be non-zero-diff. Testing with the GCM has shown zero-diff from c12 to c720, so we might be good, but let's be safe.

So, I made a branch here: `test-esmf810` that moves ESMA_env to use ESMF 8.1.0. I humbly ask @biljanaorescanin to please test and run this. My guess is it'll be zero-diff, but let's see.

Also: This branch is **_Intel-only_**. I haven't built a GNU Baselibs for this yet and all the GNU tests would do is just go back to the current one. So I guess it would pass :smile:

**Comment by biljanaorescanin** [comment]
Tests are zero diff for Intel. I suppose since there is PR now on GEOS_gcm libs for GNU are ready as well?

**Comment by mathomp4** [comment]
I do have some for GNU that I haven't tested yet. Once I do, I'll point you to them :)

**Comment by mathomp4** [comment]
Oh nuts. I have to update the nightly tests to use the 6.1.0 GNU! Thanks for the reminder!
