### ISSUE TITLE
determining photosynthetically active radiation from SWdown if unavailable from forcing inputs

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#378]
@weiyuan-jiang @biljanaorescanin :

Photosynthetically active radiation is **always** needed by Catchment in the form of "direct" and "diffuse" components (PARdrct and PARdffs, a.k.a. DRPAR and DFPAR, resp.)  If PAR info is not available from the forcing dataset, PAR is set to a constant fraction of SWdown.  This happens in subroutine ApplyForcePert(), deep in the LandPert GridComp:

https://github.com/GEOS-ESM/GEOSldas/blob/98c40e4bff6f781bc8d44d41cc30d8cc3dc6a304/src/Components/GEOSldas_GridComp/GEOSlandpert_GridComp/GEOS_LandPertGridComp.F90#L2150

If I understand correctly, GEOSldas always goes through this part of ApplyForcePert(), even when we run a single member model simulation without perturbations.

The code would be **much** clearer if we set PARdrct and PARdffs to the fraction of SWdown in subroutine get_forcing(), right after the big "if" block that selects the forcing reader and prior to exiting get_forcing().

Does this make any sense?  To be perfectly honest, though , I'm not sure I fully understand how we end up with "good" PAR values to pass into Catchment if they're not provided by the forcing reader.

For now, please take a look when you get a chance, but don't do anything.  I'm in the process of revising some of the forcing stuff in connection with Biljana's ERA5 reader.

**Comment by biljanaorescanin** [comment]
@gmao-rreichle @weiyuan-jiang 
I was digging into my code printouts for both PARs. For both variables wherever I print them the values are -9999.000 (i.e. nodata_generic). I've noticed that in LDAS_RepairForcing.F90 
https://github.com/GEOS-ESM/GEOSldas/blob/98c40e4bff6f781bc8d44d41cc30d8cc3dc6a304/src/Components/GEOSldas_GridComp/Shared/LDAS_RepairForcing.F90#L494
the if statement block requires .false. value of LDAS_is_nodata(met_force(i)%PARdffs) in order to execute. This variable is always set to .true. (when called from get_forcing() ). So, my understanding is that the if block should be looking for .true. instead of .false. (i.e., the .not. part should be removed). However, when I do this (remove the .not. boolean), PARs end up being zeros (meaning, I am still not getting values I suppose to - i.e. halves of SWdown).

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang @biljanaorescanin :

The following branch by @weiyuan-jiang is a first draft of how the present issue can be addressed:
https://github.com/GEOS-ESM/GEOSldas/tree/feature/wjiang%2Fclean_up_forcing_par

However, the branch still needs some cleanup to deal with the asymmetric use of nodata_generic (for PAR and SWnet) and nodata_forcing (for PAR and SWnet).

When I started working on this, I realized that we can simplify get_forcing() even more.  Because of some earlier cleanup, we can now have only one call to check_forcing_nodata() and repair_forcing() right after the long if block that selects the desired forcing reader, instead of having to call these subroutines separately for each reader.  (The optional arguments for repair_forcing() differ between GEOS and the other forcing datasets, but this can be addressed easily.)  This will greatly simplify how we address the nodata issue.

However, I don't want to make these changes in Weiyuan's branch because Biljana's branch with the ERA5 reader has a lot of conflicting changes in the exact same places 
https://github.com/GEOS-ESM/GEOSldas/pull/377
Unfortunately, Biljana's branch is a mix of forcing cleanup and a new ERA5 reader, and it's still in flux. 

I suggest that I will port the changes from Weiyuan's branch into Biljana's branch and put my additional cleanup on top of it once we have re-tested Biljana's branch for 0-diff.   @biljanaorescanin : can you please retest your branch?  if your problems are limited to the ERA5 reader, I can port Weiyuan's changes and add my cleanup. If we do not get 0-diff, I'll have to revisit my earlier cleanup on Biljana's branch.

**Comment by biljanaorescanin** [comment]
@gmao-rreichle All tests passed on ERA5 reader PR.

**Comment by gmao-rreichle** [comment]
Addressed with PRs #377 and #388
