### ISSUE TITLE
remove SWnet from met_force_type;  no longer read SWnet from GEOS forcing data

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#385]
@weiyuan-jiang 
When you get a chance (next week is fine!), can you please take a look at the following and see if there's anything obvious that I got wrong? 

I was hoping to remove the reading and processing of SWnet inputs in the met forcing.  SWnet is no longer used and only makes LDAS_Forcing.F90 etc more complicated than need be. 
I created a new branch (feature/borescan_era5_reichle_removedSWnet) from Biljana's branch of PR #377 (feature/borescan_era5) as of this morning.  Here's the (two-dot) difference:
https://github.com/GEOS-ESM/GEOSldas/compare/feature/borescan_era5..feature/borescan_era5_reichle_removedSWnet

Unfortunately, I must have messed up something, probably in the ESMF connections.  The nightly conus/model and global/model tests "passed" as expected, with the only "failure" being the expected lack of SWnet data in the "lfs" HISTORY output.
However, the global/assim test now fails to run.  The code crashes after initializing the "NIRDFs" albedo scaling parameters and before writing the "ldas_smapL4SMlmc" output file.  The error log only refers to elements of Baselibs.  I didn't try the debugger, mostly for lack of time and expertise.

Thanks, - R

PS: My global/assim test is at [discover nobackup]/rreichle/SystemTests/runs/LDAS_GLOBAL/assim/CURRENT

**Comment by weiyuan-jiang** [comment]
I am testing it again. I believed NCCS system went wrong sometime last Friday

**Comment by weiyuan-jiang** [comment]
There are many SWNET in GEOSgcm_GridComp. I am wondering if it is enough to just remove the variable from here in GEOSldas. I will keep test it.

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : Thanks for taking a look.  There's a key difference between two kinds of SWnet variables:
(1) SWnet as modeled in the GCM GridComp: This is computed by first diagnosing the albedo from a combination of look-up table values and MODIS scaling parameters (bcs) along with snow fraction, and then this parameter-based albedo is used together with SWdown to compute SWup and ultimately SWnet.
(2) met_force%SWnet: This is limited to GEOSldas and is read along with the other met forcing data.  It is the net SW from the entirely separate AGCM run that provided the GEOSldas forcing data, e.g., MERRA; MERRA-2; G5ADAS, a.k.a. FP.  This variable is obsolete and should not be used or needed anywhere. This is the one we're trying to get remove from the code.
I'm afraid I can't blame this on Discover issues last Friday.  I ran the test twice on Friday, and both times the CONUS and GLOBAL model tests passed (except for the expected diff in the lfs HISTORY output) but the GLOBAL/assim run failed.
cc: @biljanaorescanin

**Comment by gmao-rreichle** [comment]
The problem with the first commit and the run failures was that repair_forcing() was called first for PARdrct and then for PARdffs, which resulted in bad numbers for PARdrct.  This was fixed by improving the interface to repair_forcing().
Addressed with #386
