### ISSUE TITLE
pre-release version mistake

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSldas#39]
@mathomp4 
We made a mistake with release versions. the 4 in v4.17.8-beta.0 was referring to the module in cvs. In actuality, this:
https://github.com/GEOS-ESM/GEOSldas/releases/tag/v4.17.8-beta.0
should be named:
```v17.8.0-beta.0```

Is the solution to make a duplicate tag? I'm assuming by convention we should not delete even incorrect tags.

**Comment by mathomp4** [comment]
It is a good idea not to delete a tag as someone might have used it. I'm guessing it's possible to create a release at previous commit. If so, I'd probably draft a new one there and let people know in the description/title about the bad tag name. I was just going by what the tag looked like on CVS.

**Comment by JustinPerket** [comment]
> I'm guessing it's possible to create a release at previous commit

Yes, though you can only make releases on Github from _recent_ commits, you can push a tag to that older commit ID https://github.com/GEOS-ESM/GEOSldas/commit/9519678d09a94e1c7d47e28a86b698700aaf05fe, and then make a (pre-)release from that.
@mathomp4, permission to append your description of `releases/tag/v4.17.8-beta.0` to point out this situation when I've done this and created `releases/tag/17.8.0-beta.0` ?

**Comment by JustinPerket** [comment]
tag `17.8.0-beta.0` now created. The erroneously named tag `v4.17.8-beta.0` still exists. I update the intial release to point to the correct tag name.

A similar name issue: tag `v4.17.8-beta.1 ` now has a duplicate tag `17.8.0-beta.1`

**Comment by mathomp4** [comment]
Saw this too late, but yeah, use the text. I just wrote down stuff when I made it. 😄
