### ISSUE TITLE
vegdyn restart problem for reduced-domain ensemble run starting from reduced-domain single-member run

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#468]
@gmao-qliu, @weiyuan-jiang:
I'm catching up on a few random GEOSldas issues... See the question below from Alex Gruber about restarting a reduced-domain ensemble simulation from a reduced-domain single-member spin-up.  According to Alex's experience, it looks like in his case ldas_setup only created the proper (reduced-domain) vegdyn restart for the first ensemble member and ended up producing global vegdyn restarts for the other ensemble members.
I don't think we've exercised this particular use case here.  I think Qing usually creates a global, single-member spinup, then runs a global ensemble, and then restarts reduced-domain ensemble simulations from the global ensemble simulation.  (Qing, is this correct?)
Alex got around this by manually replacing the global vegdyn restarts for the other ensemble members with the reduced-domain vegdyn restart, so it's not urgent, but it looks like this may need fixing.

cc: @alexgruber, @biljanaorescanin 

---------------------------------------------------------------------------------------------
From: Alexander Gruber <alexander.gruber@kuleuven.be>
Sent: Monday, September 13, 2021 10:26
To: Reichle, Rolf H. (GSFC-6101)
Subject: [EXTERNAL] GEOSldas question

[...]

I’m now working with GEOSldas (v17.9.4) and ran into a problem with the restart files:

I first made a 25 year deterministic spin-up, which I ran it over the U.S. only, using the restart files that you gave me for the global domain (SMAP_Nature_v8.3_M36).

This worked just fine and starting from this spin-up, I wanted to spin up an ensemble for 1 year over the same domain (the U.S.).

However, here GEOSldas crashed because only the vegdyn_internal_rst file that is created for the first ensemble member (by “ldas_setup”) had the correct domain (the U.S.), whereas the vegdyn_internal_rst files for all other ensemble members have been re-created for the global domain.

Have you ever encountered this issue and is this perhaps something I can solve with a particular setting? Right now I circumvent it by manually replacing all vegdyn files with that of the first ensemble member.

**Comment by weiyuan-jiang** [comment]
Ok, I will take a look at it. Are all members' vegydyn restarts are the same?

**Comment by gmao-rreichle** [comment]
> Ok, I will take a look at it. Are all members' vegydyn restarts are the same?

From what I understand, the ens0000 vegdyn restart is good for the reduced-size domain, and the vegdyn restarts for ens0001-ens00xx are all identical but for the global domain (and thus don't work for the reduced-size domain).  It looks like ldas_setup's functionality for `Nens>1` is not fully consistent with `"if (domain-not-global)"` .

**Comment by weiyuan-jiang** [comment]
PR #475 passes nightly test and solves this issue.
