### ISSUE TITLE
mepo consistency check in parallel_build.csh?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#470]
Hi @mathomp4:
Currently, `GEOSldas/parallel_build.csh` does `mepo clone` only if `./@env` is not present (I think).  After `mepo clone` has run once, it typically won't kick in again.
Occasionally, the external repositories that were cloned initially go out of sync with what I'm doing in the GEOSldas repository.  That is, the externals would need to be updated, but I usually forget to keep the externals in sync and then the build fails for reasons that are difficult for me to understand.  
I recognize this is entirely a user error.  But for a casual user such as myself, it's sometimes hard to remember.  
Is there a simple way for `parallel_build.csh` to detect whether the externals are out sync with what's in `GEOSldas/components.yaml` and, if so, query the user if they want to continue with the build?
The user could then say "yes" and proceed with the build, or say "no" to interrupt the build in the knowledge that user action is needed to fix whatever got out of sync. 
I'm **not** looking for parallel_build.csh to try and get the externals back into sync.  I don't think that would be possible or desirable. 
Thoughts?  Thanks!
cc: @weiyuan-jiang, @biljanaorescanin

**Comment by mathomp4** [comment]
@gmao-rreichle  I'm not sure this is too possible at the moment with mepo or even git. I'll cc in @tclune so he can comment too.

First, if you are using a versioned tag this should *NEVER* happen. If so, then that means someone pushed a Semver tag on a GEOS-ESM repo and that should not happen. Period.

Now, if your super-clone had branches in the `components.yaml` well then that is hard. Git clones are a snapshot in time of a repository. If you clone a branch, well, you get the HEAD of that branch at that time. If you want updates to that branch, you'd have to fetch and merge (aka pull) those updates yourself. 

I'm not sure how to best support this. I mean, if a user has decided to clone a branch at a specific point in time, they decided to do that. If I ever do this sort of thing, I either have to remember I did this, or I just re-clone from scratch again. 

I suppose maybe you could go through every single repo and see if it is on a branch and then see if there are updates to that repo? I'd have to really think about how to get this into mepo. It wasn't designed for that for sure. But there are probably git ways to see if you are behind the head of a branch

**Comment by tclune** [comment]
@gmao-rreichle I'm happy to discuss further if you don't think our responses above are sufficient.   Ping me on Teams.
