### ISSUE TITLE
Throughput with fewer than 28 processor-per-node on haswell?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#471]
@weiyuan-jiang, @biljanaorescanin: 

At the modeling meeting today, Bill reported that haswell nodes perform better if not all processors are used.

Yury then posted the following in Teams chat:

```
Tested a coupled model on haswell nodes with 24 tasks per node instead of using full node. 
Throughput bumped from 30 to 55 days/day. Very impressive speedup, but this is still much 
slower than S2Sv3 model. If I interpret timing data correctly, the bottleneck is MOM6.

Times for GCM
TOTAL : 1863
AGCM : 567
OGCM : 1262

Times for MOM6
TOTAL : 1212
RUN : 1158

This is not what we previously experienced in coupled model, bottleneck was always AGCM. 
Akella, Santha (GSFC-6101) we may need to investigate what may be wrong in MOM6 setup.
```

Not sure if this is something that might also apply to skylake.  We should test this for GEOSldas and adjust the recommended processor-per-node settings accordingly if it makes a difference.

**Comment by biljanaorescanin** [comment]
[node_testing.pptx](https://github.com/GEOS-ESM/GEOSldas/files/7556417/node_testing.pptx)

Few slides addressing this issue.

**Comment by gmao-rreichle** [comment]
@biljanaorescanin's slides (attached in previous comment) suggest that wall time and model throughput are mostly unchanged when only 24 of the 28 processors on Haswell nodes are used, and likewise for using 36 of 40 processors on Skylake nodes or 45 of 48 processors on Cascade Lake nodes. 
It is noteworthy that wall time does **not** increase when between 5 and 15% fewer processors are used.  But neither does wall time decrease, so it's best to stick with the existing recommendation in the "batinp" sample file (originating in "ldas_setup"):
`# - ntasks-per-node  = number of tasks per node (typically 46 for cascade lake*, 40 for skylake, and 28 for haswell nodes)`
cc: @biljanaorescanin @gmao-qliu @weiyuan-jiang @saraqzhang @gmao-jkolassa
