### ISSUE TITLE
Convective rainfall and impact on Louis turbulence (Redelsperger et al 2000) 

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#477]
The Louis surface turbulence scheme is routinely used in off-line (land-only) GEOSldas simulations.  This scheme uses liquid convective precip inputs (PCU) inputs to compute a correction to the wind speed ("gustiness" parameterization; Redelsperger et al 2000), which ultimately impacts surface turbulent fluxes.
Because subroutine catchment() does not distinguish between convective and large-scale rainfall, the GMAO precipitation corrections algorithm puts "missing" precipitation arbitrarily into large-scale rainfall and sets convective rainfall to zero.
Also, the ERA5_LIS forcing only provides total rainfall, and the ERA5_LIS reader arbitrarily assigns all of it to large-scale rainfall and always sets convective precipitation to zero.  That is, when using Louis surface turbulence, a simulation using ERA5_LIS forcing sees slightly different physics from a simulation that uses MERRA-2 forcing.
There may be other situations where convective rainfall is set to 0.
There probably isn't much that can or should be done to "fix" this, but it would be good to quantify the impact of the Redelsperger et al (2000) correction. 
At some point, we should perhaps run and compare a pair of simulations with, say, (uncorrected) MERRA-2 forcing. In one simulation, PCU should remain as is from the MERRA-2 "int" forcing data.  In the other simulation, we should artificially disable the Redelsperger et al (2000) correction in louissurface().

@gmao-qliu @rdkoster @gmao-jkolassa

**Comment by biljanaorescanin** [comment]
[Redelsperger_Issue_477.pptx](https://github.com/GEOS-ESM/GEOSldas/files/7645992/Redelsperger_Issue_477.pptx)

Please see attached slides, differences we see with and without applying correction are relatively small.

**Comment by gmao-rreichle** [comment]
Many thanks, @biljanaorescanin, for the results and attaching your slides to the discussion.  The differences seen with and without the Redelsperger et al correction turn out to be quite small.  There is no need to revisit how existing precipitation datasets treat convective vs large-scale precipitation.  
New or revised versions of observation-corrected precip datasets or surface met forcing readers (such as for S2S and ERA5) should attempt to maintain the distinction between convective and large-scale precipitation to the extent possible.
cc:  @gmao-qliu @rdkoster @gmao-jkolassa @lcandre2 @jpark50
