### ISSUE TITLE
Using Open MPI's mpirun  instead of ESMA mpi to run OpenMPI 

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSldas#49]
Note this locks you in forever to Open MPI. And it's probably not the best way to call Open MPI's `mpirun` either.

_Originally posted by @mathomp4 in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjAwMzc0MTgzOnYy/pull_request_review_threads/discussion_

**Comment by JustinPerket** [comment]
@weiyuan-jiang found that open mpi is faster, but can we still use $GEOSBIN/esma_mpirun, @weiyuan-jiang ?

**Comment by weiyuan-jiang** [comment]
We certainly can try.  Matt gave me the mpirun command. Maybe we can see if the esma_mpirun can implement that command line

**Comment by gmao-rreichle** [comment]
We are now using esma_mpirun on dev/MAPL-2.0.  
Reopening to keep us reminded that this still needs to get merged into "develop" and ultimately "master"

**Comment by gmao-rreichle** [comment]
closing after talking with Weiyuan.  It's done.
