### ISSUE TITLE
GEOSldas version info in GEOSldas/CMakeLists.txt

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#513]
@mathomp4, @weiyuan-jiang:
I just noticed that GEOSldas version info is encoded in Line 7 of GEOSldas/CMakeLists.txt:
https://github.com/GEOS-ESM/GEOSldas/blob/8ef1476258198752af063a4b7c49f90c8b4c03da/CMakeLists.txt#L7
The most recent GEOSldas release is v17.10.0, and we did not update CMakeLists.txt to match the increased "minor" version number.
Is the GEOSldas version info in CMakeLists.txt really necessary?  It's difficult to remember to edit this file prior to issuing a release.  This is even more pertinent now that we're planning to increment the "minor" version number much more frequently.
Please advise, thanks.

**Comment by tclune** [comment]
@gmao-rreichle We too had/have trouble remembering to update this prior to commits.  Have gotten better over time, but still miss.    As @mathomp4 explained, at the fixture level there are few if any consequences to this, so feel free to rip it out. (If we are wrong, and CMake requires something - make it obviously bogus like `0.0.0`)    For libraries though this information is very important as upstream packages may require a certain minimum version or change logic depending on what version is available.   From that perspective it is most important to get the "major" version correct, and maybe "minor" on occasion.    But even "patch" changes for bug fixes could in theory be important for upstream projects no know.

It would be nice to somehow enforce that either this entry updates with GitHub releases or GitHub releases "guess" version from this entry.   But enough exceptions, that only good process is possible.    Have a checklist for the things that must be done before each release ...  (And then get someone more reliable than myself to execute said list!)

**Comment by gmao-rreichle** [comment]
Thanks, @mathomp4 and @tclune, for the info.  I'm leaning towards removing the Version entry from CMakeLists.txt for the time being.  
We could probably manage to remember updating CMakeLists.txt with a checklist-based approach.  I'm getting better at editing Changelog.md prior to issuing the Release, so I "only" have to remember to edit CMakeLists.txt along with Changelog.md.
But, as you say, having the version info is not as critical for Fixtures.  Perhaps most importantly, users will edit/modify GEOSldas releases without changing the version info in CMakeLists.txt.  That is, in many instances, the report in the run log wouldn't match the build that users actually run.   
Perhaps it's possible during the build to check the sandbox src code against the CMakeLists.txt-specified version from the repository and then automatically remove the version info from CMake if there are discrepancies.  But even if that is theoretically possible, I think it'd be taking it too far for science s/w such as GEOSldas.  
cc: @weiyuan-jiang @biljanaorescanin

**Comment by mathomp4** [comment]
@gmao-rreichle I suppose you could put a big Markdown comment in the Changelog. I've done that in some places :)

**Comment by tclune** [comment]
Some wisdom here.   Apparently some have figured out how to generate cmake version info from the git tag.   This would not be useful during the build itself, but would be useful for upstream projects.   Might be worth considering for us.

https://github.com/jrl-umi3218/jrl-cmakemodules/issues/91

**Comment by gmao-rreichle** [comment]
Addressed with #516.  Closing.
