### ISSUE TITLE
Rethink organization of mwRTM parameter inputs

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#533]
PR #521 introduces the rc variable `MWRTM_PATH:`, which is the path to the mwRTM parameters file(s).    PR #521 also introduces a new input file, `vegopacity.bin`, that contains the seasonally-varying climatology of the L-band vegetation opacity. 

The mwRTM inputs are similar to the BCS inputs in that there are static parameters (`mwRTM_param.nc4`) that make it into a restart file (for mwRTM, the GEOS LandAssim GridComp) and seasonally-varying climatological parameters (`vegopacity.bin`) that are read via `MAPL_ReadForcing()`.
  
Unlike the processing of `BCS_PATH:`, however, the processing of `MWRTM_PATH:` does not include, I think, the experiment tile space (or resolution) in the directory tree, nor are the mwRTM files necessarily stored in a directory tree that includes the tile space as a directory.  Note that recent versions of the mwRTM parameters in the SMAP life-of-mission project space are already stored with the resolution encoded in the directory tree:
/discover/nobackup/projects/gmao/smap/SMAP_L4/L4_SM/bcs/RTM_params/RTMParam_SMAP_L4SM_v004/SMAP_EASEv2_M09/

Going forward, mwRTM parameter directories should follow the template of BCS directories, and GEOSldas preprocessing should use the resolution information to assemble the full path to the mwRTM parameter files.  Unless I misunderstood the current code, this probably requires minor, 0-diff modifications in ldas_setup and likely breaks the assim nightly tests. 

cc: @weiyuan-jiang @gmao-qliu @saraqzhang @biljanaorescanin

**Comment by weiyuan-jiang** [comment]
I didn't see the folder.   /discover/nobackup/projects/p51 @gmao-rreichle

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang: Sorry, should have used the generic path:
/discover/nobackup/projects/gmao/smap/SMAP_L4/L4_SM/bcs/RTM_params/RTMParam_SMAP_L4SM_v004/SMAP_EASEv2_M09/

**Comment by weiyuan-jiang** [comment]
> @weiyuan-jiang: Sorry, should have used the generic path: /discover/nobackup/projects/gmao/smap/SMAP_L4/L4_SM/bcs/RTM_params/RTMParam_SMAP_L4SM_v004/SMAP_EASEv2_M09/

Can we just provide this as MWRTM_PATH ? or  You want ldas_setup to deduct MWRTM_PATH from BCS_PATH ?

**Comment by gmao-rreichle** [comment]
My thought was to provide `MWRTM_PATH:` independently from `BCS_PATH:`.  The reason is that the BCS data are controlled by a different group than the MWRTM data.  The idea is to have the dir tree look similar below the top-level version directory.  In the example above, the exeinp file would have:
MWRTM_PATH: /discover/nobackup/projects/gmao/smap/SMAP_L4/L4_SM/bcs/RTM_params/RTMParam_SMAP_L4SM_v004/
Then ldas_setup would find the mwrtm_param.nc4 and vegopacity.bin files in the appropriate resolution sub-directory and place the (potentially zoomed-in) vegopacity.bin[.domain] file and links to it into the ./input directory. 
I hope this makes sense.

**Comment by weiyuan-jiang** [comment]
Then we need to provide a sub-directory name for the input file.  This is inconsistent with how we specify BCS_PATH which already contains resolution sub-directory.  We can copy the last piece (sub-directory) from the BCS_PATH though if you like.

**Comment by gmao-rreichle** [comment]
I see, thanks.  Sorry, I haven't had the time to look up all the details and think this through...  So, `EXP_DOMAIN:` is just the name of the domain, and "resolution" is essentially the basename of the `BCS_PATH:`. For global runs, the two are typically identical, but not for regional domains, for obvious reasons. 

I see three options:
1) Specify both `BCS_PATH:` and `MWRTM_PATH:` with basename being the "resolution". This is asking for the same info twice and requires matching basenames.
2) Specify `BCS_PATH:` with basename being the "resolution" and `MWRTM_PATH:` without, and then obtain the "resolution" for `MWRTM_PATH` from `BCS_PATH:`.  This avoids asking for the same info twice but is asymmetric.
3) Introducing a new resource parameter `BCS_RESOLUTION:` (or perhaps `TILE_RESOLUTION:`?) that is then appended by ldas_setup to both `BCS_PATH:` and `MWRTM_PATH:`.  Incidentally, this is also consistent with GEOSldas [documentation](https://github.com/GEOS-ESM/GEOSldas/blob/v17.10.0/doc/README.MetForcing_and_BCS.md), which is actually not quite right at the moment because the documentation specifies BCS_PATH: without the "resolution" basename.

I'm leaning towards option 3 because it's cleanest, but it will break every single test case (not just the assim cases where the interface change is limited to MWRTM_FILE --> MWRTM_PATH).  But since we're introducing an interface change already, now's the time to change how BCS_PATH: is interpreted.  '

Thoughts?

**Comment by gmao-rreichle** [comment]
Addressed with #521
