### ISSUE TITLE
Are the two input files for scale  the same?

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#549]
https://github.com/GEOS-ESM/GEOSldas/blob/433ee5c2c15c7eb0d8ac7614ae5de17b354fab27/src/Applications/LDAS_App/process_rst.csh#L356-L372

it seems to me the two input files for Scale program are the same. 1) The first step is regriding. The output cdrc1, cdcr1 and vgwmax are calculated from BCs.  2) For the second step, the three output are still from the same BCs. So they are supposed to be the same.  3) the third step is scaling, it seems to me it is more like re-calibrating so the parameters become more consistent. If so, we only nee one restart for the scaling purpose.  Please let me know if my understanding is correct or not. @gmao-rreichle @gmao-jkolassa

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang: One more thought (following the discussion at our tag-up meeting this morning). After scanning through `process_rst.csh` in its entirety, I'm no longer sure that the hard-wired number ("26") in Line 372 is correct:

`${SCALE} OutData.1/M2Restart OutData.2/M2Restart ${MODEL}_internal_rst $SURFLAY 26 $WEMIN_OUT `

I'm wondering if "26" needs here to be replaced with `$WEMIN_IN`.  If this line is **only** used for MERRA-2 restarts, WEMIN=26 is correct.  But if this line is ever used for re-tiling restarts other than MERRA-2, the "26" number may be incorrect.   For example, Line 255 seems to copy a GEOS-FP ("G") source/origin restart file into the file `M2RESTART`:

`/bin/cp -p $rstfile $EXPDIR/$EXPID/mk_restarts/InData/M2Restart` 

Also, the if blocks in Lines 273-321 could (correctly) result in $WEMIN_IN=13 (if a newer GEOS FP restart is used as the source/origin restart).  In other words, it's possible that the hard-wired "26" in Line 372 is a bug.

**Comment by weiyuan-jiang** [comment]
@gmao-rreichle Thanks. I think I understand this now. old restart is re-tiled and the new restart has new BC in it.   closed

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang, thanks for the update.  I'm still not convinced that the hard-wired "26" is correct, see my comment above.  I'm reopening the issue to remind us that this still needs to be addressed.

**Comment by gmao-rreichle** [comment]
Looks to be correct in `process_rst.py` as of 29 Jun 2023.
