### ISSUE TITLE
issue with debug and make_bcs for ease grid

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSldas#552]
When running boundary conditions package if we compile GEOSldas with debug flag 
./parallel_build.csh -debug 
Package compiles successfully, but during make_bcs run I get an error and abort for ease m9 grid. 

<img width="674" alt="Screen Shot 2022-05-16 at 10 01 36 AM" src="https://user-images.githubusercontent.com/68251545/168610329-957a8de2-e982-449e-854f-23bc85c59b4a.png">

I do not have any issues with normal compilation so we never noticed this before.

**Comment by gmao-rreichle** [comment]
What is the bcs version selected when you get the floating point error?   NLv3 or NLv4?  NLv5? 
What tag GEOSgcm_GridComp version (tag or branch)?

**Comment by biljanaorescanin** [comment]
I ran from GEOSldas Develop NLv3 with ease M09.

**Comment by gmao-rreichle** [comment]
Will be addressed with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/601
See also https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/596
