### ISSUE TITLE
Moving GEOSldas Nightly Tests to GCC 12

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#573]
A notice to @gmao-rreichle @biljanaorescanin and @weiyuan-jiang. I'd like to move the GEOSldas to use GCC 12 instead of GCC 11. My testing with GEOSgcm shows this would be a non-zero-diff change, but it seems to be the normal "compiler change" sort of difference. Here's a diff plot of T between the two compilers after 18 hours:

![T_in_stock-2022Aug15-1day-c48-GNU11 geosgcm_pro](https://user-images.githubusercontent.com/2982494/187210854-c0d8997e-ab1e-4868-9e2e-c4fadc04c654.png)

Let me know when you'd like me to try the switch in the scripts (i.e., change the `gcc11` to `gcc12` in `LDAS_CUR.csh`), and then you can compare the outputs.

**Comment by gmao-rreichle** [comment]
Thanks, @mathomp4, for the heads-up and for keeping us current!  As far as I'm concerned, any day this week is fine.  If we do indeed get non-0-diff and we can't finish verification in a day, we'd just have to make sure to keep a copy of the gcc11 reference output.

**Comment by mathomp4** [comment]
Might as well do a run now! I won't advance the Baselines and once the full run is complete, I'll move the CURRENT outputs and go back to GCC 11 until all is explored.

**Comment by mathomp4** [comment]
About as expected:

Runtype           |  Clone  |  Build  |  Build Time  |  Model Run/Compare  |  Assim Run/Compare
------------------|---------|---------|--------------|---------------------|-------------------
gnuconus          |  pass   |  pass   |  12 min      |  pass/FAIL          |  -- / --
gnuglobal         |  --     |  --     |  --          |  pass/FAIL          |  pass/FAIL
gnuglobalcs       |  --     |  --     |  --          |  pass/FAIL          |  pass/FAIL
gnuglobalcnclm4   |  --     |  --     |  --          |  pass/FAIL          |  -- / --
gnuglobalcnclm45  |  --     |  --     |  --          |  pass/FAIL          |  -- / --
gnudebugconus     |  --     |  pass   |  14 min      |  pass/pass          |  -- / --

**Comment by gmao-rreichle** [comment]
Per her email of 30-Aug-2022, @biljanaorescanin looked at these tests on 29-Aug-2022 found differences to be roundoff.
This morning (while Discover was still accessible), I checked LDAS_GNUGLOBAL/assim in "PREVIOUS" (because last night's automated test is now in CURRENT) against the gcc11 BASELINE.  This check also confirmed roundoff differences.
@mathomp4:  When you get a chance (and Discover is available again), please implement the change to gcc12 in the LDAS test suite.

**Comment by mathomp4** [comment]
@gmao-rreichle I will. And thanks to @biljanaorescanin for getting a look in. I opened my laptop and I had a terminal right in the runs directory to save the GCC 12 and...just got busy yesterday!

I'll make the change tomorrow.
