### ISSUE TITLE
Build Error in Nightly Runs

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#577]
All my LDAS builds last night failed with multiple compile errors in `SaltIntSplitter.F90`:
```
/discover/nobackup/mathomp4/SystemTests/builds/LDAS_CONUS/CURRENT/GEOSldas/src/Components/GEOSldas_GridComp/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltIntSplitter.F90(105): error #6460: This is not a component name that is defined in the encompassing structure.   [GET_GLOBAL_VAR]
     global     => Incfg%get_global_var()
```
This is from a PR from @weiyuan-jiang (https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/623) which requires MAPL 2.25.

So the solution is...update to MAPL 2.25. I'll make a PR.

There have been other updates in the GEOSgcm as well, but I'll do those in a separate PR so that @biljanaorescanin can test more fully.

**Comment by weiyuan-jiang** [comment]
Issue solved after bringing new MAPL
