### ISSUE TITLE
Comparison error in GNUGLOBAL/assim test 

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#582]
The GNUGLOBAL/assim test conducted by @gmao-rreichle for #578 failed the comparison.
The same test conducted by @weiyuan-jiang passed, as did the automated nightly test of 2022-09-09.
The failed test was moved to here:
/gpfsm/dnb31/rreichle/SystemTests/runs/LDAS_GNUGLOBAL_20220909/
The differences are likely roundoff (confirmed by @gmao-rreichle, 10 Sep 2022 12:03h).
Comparison of the GEOSldas log files of the GNUGLOBAL/assim tests by @gmao-rreichle and @weiyuan-jiang suggests that some variables are not initialized by default in gcc12.  OBS_PARAM_NML differs in some fields such as %SPECIES and %ANG.  The fields that differ should not be used and therefore cannot by themselves explain the comparison failure.  But the lack of initialization in these fields suggests that other variables might also not be initialized in gcc12.  OBS_PARAM_NML is initialized to 0 in the standard-optimization Intel run.  It is not clear if they were initialized in gcc11.  
Maybe the lack of initialization explains the seemingly intermittent nature of the comparison failure?  
It is also possible that something is wrong with the failed test itself, but I don't see what that could be.

**Comment by gmao-rreichle** [comment]
I re-ran the GNUGLOBAL/assim test once yesterday, and it passed, as did the automated nightly test.  I suppose we can just wait to see if the failure happens again in the automated nightly tests.

**Comment by gmao-rreichle** [comment]
Another data point: The automated nightly GNUGLOBAL/assim test of 2022-09-12 failed.  A quick inspection suggests that this could be similar to the failure of my test of 2022-09-09.  I'll take a closer look tomorrow.

**Comment by gmao-rreichle** [comment]
I plotted the 2017-10-16, 0z ObsFcstAna output from the automated GNUGLOBAL/assim test of 2022-09-12 vs. the BASELINE.  Differences are consistent with roundoff.  (The contents of this ObsFcstAna file are from the tail end of the test run and the comparison should fail if there are any differences at all.)  
Interestingly, the automated test of 2022-09-12 is zero-diff vs. my own test run of 2022-09-09.  
Could the result be processor-dependent?  Does the automated test prescribe the processor?

**Comment by weiyuan-jiang** [comment]
In our link.j we specify
#SBATCH --nodes=4 --ntasks-per-node=28
I am not sure where this job would be sent. I think it is possible to be sent to cas instead of hashwel

**Comment by weiyuan-jiang** [comment]
At least we can test it by ourself by specifying the destination of the job.

**Comment by gmao-rreichle** [comment]
> `#SBATCH --nodes=4 --ntasks-per-node=28`

I agree this may be a concern.  I never quite trusted that we **for sure** end up on haswell when just specifying "ntasks-per-node=28".
@weiyuan-jiang, can you submit three GNUGLOBAL runs, one on each of the currently available processor types?  (i.e., haswell, skylake, cascade lake)
We can then compare the output of these three runs to the existing BASELINE and to last night's CURRENT (or, equivalently, my LDAS_GNUGLOBAL_20220909/, see above)

**Comment by weiyuan-jiang** [comment]
NCCS has confirmed with me that the slurm job may be allocated to hasw, sky or cat if there is no constraint.  Three containts ( hasw, cas and sky) are used to run the tests, and the results show  hasw != cas == sky

**Comment by gmao-rreichle** [comment]
Thanks, @weiyuan-jiang, for tracking this down.  Since this wasn't an issue with gcc11, I'm guessing it's a change in the compiler flags?  @mathomp4, can you think of anything in the gcc flags that might be different with gcc12 from what we had with gcc11? 
I think we always had non-0-diff for the [GNU]GLOBAL/ASSIM when changing the layout, but we never had non-0-diff changes with a change of processor type.  It would be good to  get back to having the results be independent of processor type.

**Comment by weiyuan-jiang** [comment]
We don't know if this was an issue or not for gcc11. NCCS said the policy for the job allocation  was changed recently.

**Comment by gmao-rreichle** [comment]
> We don't know if this was an issue or not for gcc11. NCCS said the policy for the job allocation was changed recently.

Good point.  Would it be possible to determine more exactly when the policy changed?  We do know when we switched to gcc12.  If the policy change pre-dates the gcc12 update by a week or more, chances are we would have seen the issue with gcc11 if it was present in gcc11.
My statement that we didn't have the issue in gcc11 was based more on the fact that we had tested for processor-dependent results some time ago and found no differences when using standard optimization.  Also, there is still the issue with the non-initialization of the OBS_PARAM_NML variable in GNU.  The standard Intel build initializes this structure to 0.  Maybe the processor-dependency is caused by the non-initialization of some variables (rather than compiler flags)?  Or maybe the GNU compiler flags have changed to omit the initialization?  
Alas, I don't know if the initialization was happening in gcc11, per my comment above.  I suppose this could all be tested by reverting the tests back to gcc11 for a bit, or running a separate set of gcc11 tests on all three proc types.

**Comment by gmao-rreichle** [comment]
After a bit of sleuthing through my emails, I think the SLURM update happened on Tue Aug 30 and the switch to gcc12 in the LDAS tests happened on Thu Sep 1.  The SLURM update caused the comparisons to fail for silly reasons, which makes it difficult to know which tests would have passed the comparisons and which wouldn't have.  In a nutshell, the timing of the SLURM and gcc12 updates was most unfortunate, and we can't know if the processor-dependency of the gnuglobal/assim test was present with gcc11.  I suppose we could run just run the gnuglobal/assim test with gcc11 for each processor type and then compare, much like Weiyuan did for gcc12 today.  Not sure if this would enlighten us about the reason for the processor-dependency.

**Comment by mathomp4** [comment]
> Thanks, @weiyuan-jiang, for tracking this down. Since this wasn't an issue with gcc11, I'm guessing it's a change in the compiler flags? @mathomp4, can you think of anything in the gcc flags that might be different with gcc12 from what we had with gcc11? I think we always had non-0-diff for the [GNU]GLOBAL/ASSIM when changing the layout, but we never had non-0-diff changes with a change of processor type. It would be good to get back to having the results be independent of processor type.

In [ESMA_cmake v3.17.0](https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.17.0), I changed the default GNU Release flags to target `haswell` instead of `westmere` because:

1. Westmere is ancient
2. The model [crashed on with GCC 12 when built with `westmere`](https://github.com/GEOS-ESM/ESMA_cmake/issues/275) but runs with `haswell`

With the GCM, while this did change the results, as far as I remember, the answers were identical across the chips with those flags.

But, I never looked at the *Aggressive* flags. To me those are "buyer beware" and I can definitely see them giving different answers on different chip types as that uses `-march=native` so GNU is free to just pick the best instructions for whatever chip you have *built* on.

So you could get all sorts of interesting things. Build on Haswell but run on Cascade Lake could give you different answers than build on Cascade Lake run on Haswell (actually, the latter could potentially crash if some weird obscure Lake-only flag was used). I probably never see this in my GCM testing as I pretty much just build and run on Cascade Lake exclusively at the moment for consistency.

I suppose I could change the test LDAS scripts to do `sbatch --constraint=FOO` so that if nothing else all the jobs are submitted to the `FOO` nodes. 

Note: with Intel, our aggressive flags are not "as" aggressive as they just target CORE-AVX2 instructions while relaxing some restrictions. I never guarantee answer compatibility between chips with it either, but you could at least be sure a compiled executable will work on any CORE-AVX2 supporting chip. GNU doesn't really have that guarantee as we are letting the compiler do what it wants.

**Comment by mathomp4** [comment]
My only other theory is possibly this:

https://github.com/GEOS-ESM/GEOSldas/blob/6211f3ec8283de340f704592f6b71b354ee912de/src/Applications/LDAS_App/lenkf.j.template#L37-L42

The thing is, both my GCC 11 and GCC 12 `g5_modules` load MKL 2021.4 when you source them. And MKL doesn't really depend on what compiler is loaded since you'd be linking to the same files.

**Comment by gmao-rreichle** [comment]
> for the LDAS you might want to have the setup script say "if GNU, use Cas or Hasw only?"

Thanks, @mathomp4, for the insights.  But the hardware arguments that skylake nodes differ from haswell and cascade lake seemingly contradicts @weiyuan-jiang's finding for the GNUGLOBAL/assim test:

> The results show hasw != cas == sky

This also suggests that the AVX2 flag is probably ok, since the outlier in the LDAS results is haswell, which should be giving us the same result as sky as of the June 2021 comment in `lenkf.j.template`, at least for Intel.  I'm still confused but confident you can somehow resolve the mystery eventually.

**Comment by weiyuan-jiang** [comment]
@gmao-rreichle Should we initialize OBS_PARAM_NML with some defaults  ?

**Comment by gmao-rreichle** [comment]
@mathomp4, @weiyuan-jiang:
First, for the record, here's what @weiyuan-jiang found about gcc11:
```
From @weiyuan-jiang (Wed 21-Sep-2022, 15:00): 
I tried gcc 11.2 on hasw , sky and cas and found they are zero diff.  
When we moved to gcc 12, are there any compiling flags change?
```
Thanks, @weiyuan-jiang, for confirming that the gcc11 GNU tests were not dependent on the processor flavor.
@weiyuan-jiang, is the gcc11 gnuglobal/assim test result zero-diff with either of the gcc12 results?  That is, does either of the following apply: 
gcc11 == gcc12/has 
gcc11 == gcc12/sky == gcc12/cas
(They cannot both be true, per @weiyuan-jiang's comments above, but they could both be false.)
In any case, this suggests to me that the set of flags used with gcc12 indeed includes something that makes LDAS results processor-dependent.   It would helpful to avoid the dependency.  The challenge is to find out which flag(s) might cause this dependency. 
Alternatively, we could simply wait until the haswell nodes are removed.  At that point, the gcc12/gnuglobal/assim test should be ok again (assuming the baseline is from sky or cas), at least until a new processor type is introduced.   But I don't know how long it might be until haswell nodes are removed.  If we decide to stick with the current flags and wait out the haswell removal, then we should force the GNU test on either sky or cas.  The challenge then is to remember to remove the node selection once the haswells are gone, so we don't remain completely insensitive processor-dependency going forward.

**Comment by weiyuan-jiang** [comment]
Actually, gcc11 != gcc12 in three cases (hasw, sky, cas). So I guess we must have rebased the baseline to gcc12
