### ISSUE TITLE
How to calculate ur and ll

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#585]
https://github.com/GEOS-ESM/GEOSldas/blob/1fd9008683aa2fd3d1e79629773dbaeba658f9ad/src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordRoutines.F90#L375-L432

The cases here are quite limited and need to be updated to keep up with new resolution. Is there any procedure calculating ur and ll ?  The subroutine get_params should have those numbers.  @gmao-rreichle

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang, thanks for bringing this up.  Indeed, `ll_lat` and `ur_lat` can be computed from `ease_inverse ()` as follows (pseudocode):
```
ll_lat:   ease_inverse (EASELabel, r=0, s=      -0.5, ll_lat, tmplon)
ur_lat:   ease_inverse (EASELabel, r=0, s=N_rows-0.5, ur_lat, tmplon)
```
The point is that by passing in the appropriate fractional row indices (`s`), we get the lat of the edge of the northernmost and southernmost grid cells.  Note that EASE indexing is zero-based.  For longitude, just use dummy input and output.

It's best to write a simple F90 driver program for ease_inverse() to verify that the results match the numbers that are currently hardcoded.  I threw the pseudocode together from memory.  There's a good chance I got something wrong.  E.g., I'm never quite sure if s or r is for latitude.

Note that we should also have `ease_cell_area = map_scale_m**2 / 1000 / 1000`

It's almost certain that computing these numbers from scratch will result in a non-0-diff change.  That's ok, we just need to keep that in mind when we test and merge the PR for LDAS.  (There should be no impact on Raster/make_bcs in the GCM GC.)

**Comment by weiyuan-jiang** [comment]
It seems the ll_lat and ur_lat are reversed.program main
  use EASE_conv
  implicit none
  integer :: rows, cols
  real :: lat, lon
  call ease_extent('EASEv2_M09', cols, rows)
  call ease_inverse('EASEv2_M09', -0.5, -0.5, lat, lon)
  print*, 's=-0.5 :', lat, lon
  call ease_inverse('EASEv2_M09', -0.5, rows-0.5, lat, lon)
  print*, 's=rows-0.5:', lat, lon
end program

./a.out
 s=-0.5 :          85.0445938      -180.000000    
 s=rows-0.5:  -85.0445938      -180.000000

**Comment by gmao-rreichle** [comment]
Yes, sure.  EASE indexing starts at the northernmost row, so ur_lat should go with s=-0.5.  I knew I made at least one error...

**Comment by gmao-rreichle** [comment]
No action needed.
