### ISSUE TITLE
GEOSldas tests of Bill's "refactored moist" GEOSgcm_GridComp branch

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#609]
@biljanaorescanin,
Scott just mentioned to me that Bill's "refactored moist physics" branch might be merged into GEOSgcm_GridComp develop soon (within a week or so).  
Given the extent of the changes in Bill's branch, it would be prudent to test his branch with GEOSldas. 
The expectation is that we can run Bill's branch and that it's 0-diff, but that's not a sure thing. 
Bill's GEOSgcm_GridComp branch comes with associated changes in other repositories, but my understanding is that none of the other repos are needed/used in GEOSldas.  (Bill's branch does not touch GMAO_Shared.)
There may be a discrepancy with the utilities versions (incl. cmake). 
It's also possible that we can only test Bill's branch with GEOSldas once Scott has merged GEOSgcm_GridComp develop into Bill's branch, which would be the first step towards merging Bill's branch into develop. 
For now, please try a GEOSldas test with Bill's branch (or tag, see below) and see if that might work.  If it does not, wait for @sdrabenh to create an updated version of Bill's branch.
In any case, we should know if Bill's branch works with the LDAS **before** Bill's branch is merged into GEOSgcm_GridComp develop.
Thanks! 

Bill's branch (w/ ongoing development, ie., moving target):
  feature/sdrabenh/merge_v10.23.0_MSTRF

Recent stable version (tag) of Bill's branch:
  wmp_MSTRF_v06  

cc: @weiyuan-jiang

**Comment by biljanaorescanin** [comment]
@gmao-rreichle neither of these versions of Bill branch will compile for us as it is now:

<img width="1484" alt="Screen Shot 2022-12-14 at 2 02 39 PM" src="https://user-images.githubusercontent.com/68251545/207688866-4bc0ce81-ec77-47ec-ae0b-51348376cf51.png">

As you said "we can only test Bill's branch with GEOSldas once Scott has merged GEOSgcm_GridComp develop into Bill's branch" 
I will try again once @sdrabenh updates the branch.

**Comment by sdrabenh** [comment]
@biljanaorescanin @gmao-rreichle @weiyuan-jiang please test with the latest branch:

`mepo clone -b feature/sdrabenh/merge_v10.25.0_MSTRF git@github.com:GEOS-ESM/GEOSgcm.git`

or latest tag:

`mepo clone -b wmp_MSTRF_v11 git@github.com:GEOS-ESM/GEOSgcm.git`

**Comment by biljanaorescanin** [comment]
Both latest tag (wmp_MSTRF_v11) and latest branch (feature/sdrabenh/merge_v10.25.0_MSTRF) Nightly tests passed.

**Comment by biljanaorescanin** [comment]
Since Krok is now merged, I will close this issue. 
https://github.com/GEOS-ESM/GEOSgcm/releases/tag/v11.0.0
