### ISSUE TITLE
turn off/on CI tests for PRs?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#626]
@mathomp4 : How much of a burden are the Github CI build tests in the GEOSldas repo?  Is GMAO paying for this feature?  I'm asking because the CI tests kick in for every little commit, which does add up and has made group members wary of keeping PRs open during development.  
If the CI tests aren't overly burdensome and available at no cost, there's probably no need to change anything.  Otherwise, would there be a way for the user to temporarily turn off the automated testing, perhaps by introducing a new "Label" (something like "Do-Not-Autotest")?

cc: @amfox37 @biljanaorescanin @weiyuan-jiang

**Comment by mathomp4** [comment]
@gmao-rreichle The GEOSldas is not much of a burden at all. The GMAO does pay for it, but it's a cost we've been willing to pay.

In the current cycle, GEOSldas has used about 8300 credits and that's fairly consistent its usual monthly usage. Compare that to MAPL which is currently at about 70000 credits of use (and a few months ago was over 300k). This is why I recently turned off a lot of MAPL tests. We are expecting to increase our spend soon.

So no worries at the moment. You all are not doing anything bad and the CI here is teeny compared to MAPL (so many tests at one point). All LDAS is doing is building with Intel and GNU.

In fact, I've been thinking of ways to make this more efficient. One thing that annoys me at the moment is that the CI is triggered even if the only change is to, say, a README. But I've recently been pondering ways you can have GitHub Actions trigger CircleCI and GitHub *does* know about labels (CircleCI can't see that through the GitHub API).

**Comment by mathomp4** [comment]
Also, CircleCI _should_ cancel redundant tests, so if you make a lot of commits in quick succession, it's supposed to be smart enough to kill older jobs for that PR and spin up new ones.

**Comment by gmao-rreichle** [comment]
Many thanks, @mathomp4, for the insights.  So for now we won't change anything.  But do let us know if there's anything we can do to avoid unnecessary use of credits.
