### ISSUE TITLE
should treat these like lai.data and ...

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSldas#627]
https://github.com/GEOS-ESM/GEOSldas/blob/eef59e2d1b69ce8a91122cbbb4a641bdecc810f6/src/Applications/LDAS_App/lenkf.j.template#L116-L117

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang, note that this applies only to the CO2_* file.  The FPAR_* file is obsolete.

**Comment by gmao-rreichle** [comment]
Addressed in https://github.com/GEOS-ESM/GEOSldas/pull/663
