### ISSUE TITLE
EASE grid name change

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSldas#673]
In creating a `V06` set of boundary conditions for @lcandre2, we encountered problems with the EASE grid name change within the tile file. 
Currently, "ldas_setup" only works with the old name. 
For example: from legacy_bcs M36 Nlv3 in SMAP_EASEv2_M36_964x406.til
has:  `SMAP-EASEv2-M36`
but if we run boundary conditions now, we get an output with name change `SMAP_EASEv2_M36` (or most recent:  `EASEv2_M36)`

If we try to run with the new grid name, system is not flexible and won't find the tile. We get this error:

`GEOSldas::Initialize              555`

For now fix is implemented manually, by going into EASE grid set and changing the ease grid name in tile file. 
Maybe we need to implement partial name search?  Look for just `M36` and no `-` or `_`

@weiyuan-jiang @gmao-rreichle

**Comment by weiyuan-jiang** [comment]
Basically you need the MAPL fix here. Would you please give a try ?  https://github.com/GEOS-ESM/MAPL/pull/2307

**Comment by biljanaorescanin** [comment]
With this change in MAPL, both options will run. 
One downside, though, is we will have to update few repos in `components.yaml`,  env and cmake,  to make `MAPL develop branch` run with GEOSldas. I think a non-zero diff change has been been implemented a while back, so maybe we can talk when is a good time to do this. For now we have a fix and we know how to make it run if anyone needs new boundary conditions.

**Comment by gmao-rreichle** [comment]
addressed with #680
