### ISSUE TITLE
boundary conditions install dir issue 

### ISSUE THREAD

**Issue by biljanaorescanin** [GEOS-ESM/GEOSldas#686]
With addition of `milan` nodes scripts were updated to create install directory with new name to separate builds on `SLES-12` and `SLES-15.` This produces our make_bcs.py package to report error can't find install/bin dir. 

For example cube grid in make_bcs_cube.py:

if 'install/bin' not in bin_dir:
print(" please run this program in installed bin directory")
return

**Comment by gmao-rreichle** [comment]
> @gmao-rreichle Is the plan to add fix for this on top of this PR(https://github.com/GEOS-ESM/GEOSldas/pull/680)?

Maybe it's better if we have a separate PR for the Milan/SLES-12/SLES-15 fixes, but it's ok with me if we add it on top of #680.  In the latter case, please make sure to update the intro comment of #680
