### ISSUE TITLE
run ./ldas_setup from another user's install

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#699]
@weiyuan-jiang: `ldas_setup` must be run from the `./install/bin/` directory.  It appears that `ldas_setup` creates at least one temporary file (`LDAS_domain_def.nml`) in the `./install/bin/` directory:

https://github.com/GEOS-ESM/GEOSldas/blob/23f8320dac342b77ae6443a3f213fc5476aa240b/src/Applications/LDAS_App/ldas_setup#L361

This fails when the user who runs `ldas_setup` does not have write permission in the `./install/bin` directory, which normally happens when the user sets up an experiment from somebody else's build.  

Using somebody else's build for setting up an experiment works for GEOSadas and can be helpful in some situations.

Granting write permissions in `./install/bin/` to "group" or "other" is not an acceptable permanent solution.

There may be other temporary files written in `./install/bin/`.  

Can we make `ldas_setup` write such temporary files into a user-owned directory instead of `./install/bin/`?  If this is done after ldas_setup queries for the experiment directory, perhaps the temporary file could be created in the scratch directory of the experiment directory. 

cc: @saraqzhang @biljanaorescanin

**Comment by mathomp4** [comment]
I think using something as simple as `tempfile.TemporaryFile` should do this. I might give it a try...
