### ISSUE TITLE
test updated baselibs (incl. updated hdf) in GEOSldas

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#701]
@biljanaorescanin:
@mathomp4 had warned us about an hdf update late last year:
https://github.com/GEOS-ESM/ESMA-Baselibs/pull/137
It looks like this update has now happened:
https://github.com/GEOS-ESM/ESMA-Baselibs/pull/145
I assume the new Baselibs release will find its way into the next ESMA_env release.
Is there a way we can test the new Baselibs with GEOSldas before then, to avoid surprises later? 
This isn't super urgent but we need to keep it on the list of things to do.

cc: @weiyuan-jiang

**Comment by mathomp4** [comment]
@gmao-rreichle I'm still testing but it does seem to work in places.

Once I'm happy, I'll work on getting a full baselibs build up for it and then I can pass a branch for Biljana to test.

**Comment by gmao-rreichle** [comment]
Closing this issue, which is continued in #713 (closed), then #726
