### ISSUE TITLE
In GEOSldas, use only a sparse checkout of GEOS_Util?

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSldas#708]
@weiyuan-jiang : When running GEOSldas parallel_build.csh, mepo init tends to take a long time when it is getting the external GEOS_Util repo.  The latter consists of >1,000 files, and we probably only need a handful (`pre/remap_restart/*`).  For reference, the entire GEOSldas (incl external repos) consists of ~4,000 files.   
I might have miscounted, and I might be missing something else we need from GEOS_Util besides remap_restart.py.  But it's worth a try to see if we can do a sparse checkout for GEOS_Util.  When you get a chance, can you please take a look?  Thanks!

cc: @biljanaorescanin

**Comment by weiyuan-jiang** [comment]
After we have tag from GEOS_Uti,  this [PR](https://github.com/GEOS-ESM/GEOSldas/pull/711) can have sparse checkout of GEOS_Util.
Do we need sparse checkout of GMAO_Share? @gmao-rreichle

**Comment by gmao-rreichle** [comment]
> Do we need sparse checkout of GMAO_Share? @gmao-rreichle

Maybe.  I didn't look into the size of what we need relative to the total size of GMAO_Shared.  Something to look into.  Maybe just run mepo intialize and see if any repo other than GEOS_Util slows things down

**Comment by gmao-rreichle** [comment]
addressed in #711
