### ISSUE TITLE
Testing Baselibs 7.18.1 → HDF5 1.14

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#713]
Soon ESMA_env will move to use Baselibs 7.18.1 whose main change is moving from HDF5 1.10 to 1.14. GEOSgcm seems pretty agnostic to this as any HDF5 work is done through netCDF (solely I think).

But GEOSldas has [an entire file based on HDF5](https://github.com/GEOS-ESM/GEOSldas/blob/develop/src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/io_hdf5.F90), so we want to be careful.

As such, I've made a branch here:

```
feature/mathomp4/baselibs-7.18.1-ldas
```

which updates the ESMA_env to use Baselibs 7.18.1. 

I'm hoping nothing happens, all works well, and life is good. 🤞🏼 

See also #701

**Comment by gmao-rreichle** [comment]
The "CONUS" and "GLOBAL" tests passed for both Intel and GNU.  The GLOBAL/assim case is akin to running GEOSldas.x within the SMAP L4_SM system and exercises the reading of h5 files. 
The SMAP L4 ops system has additional uses of hdf (e.g., creating the h5 product files for L4_SM and L4_C), although I'm not sure if @jardizzo uses ESMA_env to build the other components of the SMAP L4_SM system (other than GEOSldas).  I'll inquire.

**Comment by mathomp4** [comment]
@gmao-rreichle Well, glad to hear GEOSldas can at least *consume* HDF5 just fine. My guess is if SMAP L4 does use Baselibs, they probably have no reason or need to use newer ones. So we could be good!

**Comment by gmao-rreichle** [comment]
Closing this issue.  Discussion continues in #726.
