### ISSUE TITLE
Error building GEOSldas with GNU: LDAS_TileCoordType.F90

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSldas#85]
If we ever want to get CI working with GEOSldas, we'll need to fix its issues with the GNU compiler. Normally, I'd try and fix everything and present a PR with the fixes, but as I'm not really good at *running* the LDAS, I'll file issues. Someone like Weiyuan can probably do them all in one fell sweep, but here's the first.

To wit, GNU has an issue with these lines:

https://github.com/GEOS-ESM/GEOSldas/blob/c9df6062b48d420accee2a206f41305a76a02153/src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90#L288-L289

https://github.com/GEOS-ESM/GEOSldas/blob/c9df6062b48d420accee2a206f41305a76a02153/src/Components/GEOSldas_GridComp/Shared/LDAS_TileCoordType.F90#L326-L327

The reason is `index()` returns an integer. In Fortran it's non-standard to do `if(integer)`. It's *doubly* non-standard to do `if(integer .OR. integer)` as `.OR.` expects logicals.

**Comment by mathomp4** [comment]
If someone wants to test this, the simplest way is to replace `@env/g5_modules` with `/home/mathomp4/GitG5Modules/SLES11/5.1.7-Github/g5_modules.gcc8`. Then when you source it, you'll get GCC/Open MPI

**Comment by weiyuan-jiang** [comment]
Now the branch dev/MAPL2.0 conforms gcc-9.1 and will be merged to develop soon

**Comment by gmao-rreichle** [comment]
closing after talking with Weiyuan.  It's done.
