### ISSUE TITLE
Spinning up restarts for GCM missing variables

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSldas#88]
Missing WW,CH,CM,CQ,FR. Current work around is to add in with ncks after the fact, or to modify GEOS_CatchGridComp with `RESTART = MAPL_RestartOptional` fo AddInternalSpec Calls for these variables. It would be nice to have an LDAS.rc option to put it in a 'GCM Spinup' mode. perhaps a modification of the is_OFFLINE logical?

I've had to do this several times by hand, and so has @saraqzhang

**Comment by JustinPerket** [comment]
This GEOSgcm_GC branch has the code change for LDAS to write out the variables needed for GCM, without requiring them itself:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/jperket/rsts-4-GCMspinup

What's left is to wrap this behavior in a switch.

**Comment by gmao-rreichle** [comment]
To  be completed as soon as we can (after Justin has left).
See Justin's previous comment about what is needed.

**Comment by gmao-rreichle** [comment]
This was merged with dev/MAPL-2.0.
